-- Generated by tiraxis-werkzeug/sql_bauen.py. Do not edit by hand.
--
-- Tiraxis and the Ethereal Bazaar, rebuilt from the client's own data: his
-- creature record and gossip from the client cache, his item pool from
-- VanityCollection, the fixed part of his inventory from a capture of the live
-- server's npc_vendor, and every price from ItemExtendedCost so the ordinary
-- vendor frame can charge Bazaar Tokens without a client patch.

-- The running rotation. It lives here rather than in the world database
-- because it is server state, not content: it changes several times a day and
-- must survive a restart, or an admin restart would silently reroll the shop.
CREATE TABLE IF NOT EXISTS `ethereal_bazaar_stock` (
  `item`          INT UNSIGNED NOT NULL,
  `extended_cost` INT UNSIGNED NOT NULL,
  `band`          TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`item`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ethereal_bazaar_meta` (
  `name`  VARCHAR(32) NOT NULL,
  `value` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
