int main()
{
    Map map;
    Player owner, other, enemy;
    owner.guid = {1};
    other.guid = {2};
    enemy.guid = {3};
    owner.cls = other.cls = CLASS_RANGER;
    owner.map = other.map = enemy.map = &map;
    other.summons = 100;
    owner.auras[520925] = {520925, owner.guid};
    other.auras[520925] = {520925, other.guid};
    enemy.friendly = false;
    Spell spell;
    SpellInfo info;
    info.SpellFamilyName = 27;
    info.SpellFamilyFlags[2] = 8192;
    ranger_petalkeeper_casts casts;
    casts.OnSpellCast(&spell, &owner, &info, false);
    assert(owner.casts == std::vector<uint32>{521222});
    spell_ascension_ranger_red_flower summon;
    summon.caster = &owner;
    summon.info.Id = 521222;
    summon.info.duration = 30000;
    assert(summon.Load());
    summon.Summon(0);
    assert(RedFlowerGuids(owner.guid).empty());
    WorldLocation destination{10, 20, 30, 1};
    summon.fixtureDestination = &destination;
    owner.failSummon = true;
    summon.Summon(0);
    assert(RedFlowerGuids(owner.guid).empty());
    owner.failSummon = false;
    summon.Summon(0);
    auto first = owner.creatures.back().get();
    assert(first->entry == 454240 && first->duration == 30000 && first->position == destination);
    assert(first->motion.idle && first->createdBy == 521222 && first->ownerGuid == owner.guid);
    summon.Summon(0);
    auto second = owner.creatures.back().get();
    summon.caster = &other;
    summon.Summon(0);
    auto foreign = other.creatures.back().get();
    assert(RedFlowerGuids(owner.guid).size() == 2 && RedFlowerGuids(other.guid).size() == 1);
    aura_ascension_ranger_petalkeeper proc;
    proc.target = &owner;
    DamageInfo damage;
    ProcEventInfo event{&owner, &enemy, &damage};
    assert(proc.CheckProc(event));
    event.hit = 0;
    assert(!proc.CheckProc(event));
    event.hit = PROC_HIT_CRITICAL;
    damage.amount = 0;
    assert(!proc.CheckProc(event));
    damage.amount = 1;
    for (int i = 0; i < 9; ++i)
        proc.AddPetals(nullptr, event);
    assert(first->GetAura(521220, owner.guid)->stacks == 9);
    assert(!foreign->HasAura(521220));
    info.SpellFamilyFlags[2] = 1;
    casts.OnSpellCast(&spell, &owner, &info, false);
    assert(!first->removed && !second->removed);
    second->samePhase = false;
    proc.AddPetals(nullptr, event);
    assert(first->GetAura(521220, owner.guid)->stacks == 10);
    assert(second->GetAura(521220, owner.guid)->stacks == 9);
    second->samePhase = true;
    spell.triggered = true;
    casts.OnSpellCast(&spell, &owner, &info, false);
    assert(!first->removed);
    spell.triggered = false;
    casts.OnSpellCast(&spell, &owner, &info, false);
    assert(first->removed && first->casts == std::vector<uint32>{521451});
    assert(!second->removed && !foreign->removed && RedFlowerGuids(owner.guid).size() == 1);
    casts.OnSpellCast(&spell, &owner, &info, false);
    assert(first->casts.size() == 1);
    first->ai.reset();
    assert(RedFlowerGuids(owner.guid).size() == 1);
    owner.auras.erase(520925);
    second->ai->UpdateAI(500);
    assert(second->removed && RedFlowerGuids(owner.guid).empty() && !foreign->removed);
    other.inWorld = false;
    foreign->ai->UpdateAI(500);
    assert(foreign->removed && RedFlowerGuids(other.guid).empty());
    aura_ascension_ranger_red_dream dream;
    dream.target = &owner;
    event.actor = &owner;
    damage.amount = 109;
    damage.type = SPELL_DIRECT_DAMAGE;
    AuraEffect effect;
    effect.amount = 10;
    assert(dream.CheckProc(event));
    dream.Heal(&effect, event);
    assert((dream.prevented && owner.heals.back() == std::pair<uint32, int32>(521643, 10)));
    damage.type = DIRECT_DAMAGE;
    assert(dream.CheckProc(event));
    damage.type = DOT;
    assert(!dream.CheckProc(event));
    damage.type = SPELL_DIRECT_DAMAGE;
    event.actor = &other;
    assert(!dream.CheckProc(event));
    event.actor = &owner;
    enemy.friendly = true;
    assert(!dream.CheckProc(event));
    enemy.friendly = false;
    owner.alive = false;
    assert(!dream.CheckProc(event));
    owner.alive = true;
    auto count = owner.heals.size();
    damage.amount = 1;
    dream.Heal(&effect, event);
    effect.amount = 100;
    damage.amount = 0xFFFFFFFF;
    dream.Heal(&effect, event);
    assert(owner.heals.size() == count);
}
