-- Generated by tiraxis-werkzeug/sql_bauen.py. Do not edit by hand.
--
-- Tiraxis and the Ethereal Bazaar, rebuilt from the client's own data: his
-- creature record and gossip from the client cache, his item pool from
-- VanityCollection, the fixed part of his inventory from a capture of the live
-- server's npc_vendor, and every price from ItemExtendedCost so the ordinary
-- vendor frame can charge Bazaar Tokens without a client patch.

DROP TABLE IF EXISTS `ethereal_bazaar_pool`;
CREATE TABLE `ethereal_bazaar_pool` (
  `item`          INT UNSIGNED NOT NULL,
  `extended_cost` INT UNSIGNED NOT NULL COMMENT 'ItemExtendedCost row that charges `price` in Bazaar Tokens',
  `price`         INT UNSIGNED NOT NULL COMMENT 'kept for readers; the client is charged through extended_cost',
  `band`          TINYINT UNSIGNED NOT NULL COMMENT '0 below 1000, 1 up to 1499, 2 from 1500',
  PRIMARY KEY (`item`),
  KEY `band` (`band`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='What Tiraxis can draw a rotation from';

DROP TABLE IF EXISTS `ethereal_bazaar_cache_pool`;
CREATE TABLE `ethereal_bazaar_cache_pool` (
  `cache_item`  INT UNSIGNED NOT NULL COMMENT 'the cache the player opens',
  `reward_item` INT UNSIGNED NOT NULL COMMENT 'one of the items it can contain',
  PRIMARY KEY (`cache_item`, `reward_item`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Former webshop-only items, by category';
