-- Generated by tiraxis-werkzeug/sql_bauen.py. Do not edit by hand.
--
-- Tiraxis and the Ethereal Bazaar, rebuilt from the client's own data: his
-- creature record and gossip from the client cache, his item pool from
-- VanityCollection, the fixed part of his inventory from a capture of the live
-- server's npc_vendor, and every price from ItemExtendedCost so the ordinary
-- vendor frame can charge Bazaar Tokens without a client patch.

-- The two lists that do NOT rotate. Both hang off vendor entries of their own;
-- no creature is spawned for them. WorldSession::SendListInventory takes a
-- vendor entry, so one NPC can open three lists.
--
-- The Stones of Retreat are added by name rather than one line per id: there
-- are 167 of them and they all cost the same.
DELETE FROM `npc_vendor` WHERE `entry` IN (900008,900009,900010,900011);

-- Convenience: 27 items, from a capture of the live server's own list.
INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`) VALUES
-- Experience and reputation
(900008,0,818059,0,0,3015),  -- Aura of Experience, 350 tokens
(900008,1,818061,0,0,2989),  -- Aura of Reputation, 200 tokens
(900008,2,818046,0,0,460),  -- Potion of Experience, 75 tokens
(900008,3,818047,0,0,10223),  -- Potion of Reputation, 50 tokens
-- Devices
(900008,4,190190,0,0,3015),  -- Loot-Transfigurator 5000, 350 tokens
(900008,5,57000,0,0,13010),  -- Lootbot 3000, 475 tokens
-- Bags
(900008,6,43345,0,0,2989),  -- Dragon Hide Bag, 200 tokens
(900008,7,1004036,0,0,2989),  -- Ironweave Bag, 200 tokens
(900008,8,1004040,0,0,3016),  -- Mekkatorque's Neverending Storage Contraption, 500 tokens
(900008,9,505002,0,0,2989),  -- Pristine Pouch, 200 tokens
-- Scrolls and tomes
(900008,10,97871,0,0,10335),  -- Craftsman's Codex, 600 tokens
(900008,11,696664,0,0,41017),  -- Keeper's Scroll: Aggramar, 10 tokens
(900008,12,1179269,0,0,41017),  -- Keeper's Scroll: Crafting Speed, 10 tokens
(900008,13,696665,0,0,41017),  -- Keeper's Scroll: Eonar, 10 tokens
(900008,14,1179261,0,0,41017),  -- Keeper's Scroll: Featherfall, 10 tokens
(900008,15,1179266,0,0,41017),  -- Keeper's Scroll: Ghost Runner, 10 tokens
(900008,16,696661,0,0,41017),  -- Keeper's Scroll: Golganneth, 10 tokens
(900008,17,696663,0,0,41017),  -- Keeper's Scroll: Khaz'goroth, 10 tokens
(900008,18,696662,0,0,41017),  -- Keeper's Scroll: Norgannon, 10 tokens
(900008,19,1179240,0,0,41017),  -- Keeper's Scroll: Steadfast, 10 tokens
(900008,20,1806961,0,0,2984),  -- Mystic Enchanting: Specialization, 150 tokens
(900008,21,3001006,0,0,2984),  -- Riding Tome: Apprentice Riding, 150 tokens
(900008,22,3001005,0,0,2989),  -- Riding Tome: Journeyman Riding, 200 tokens
(900008,23,777998,0,0,2990),  -- Tradesman's Scroll, 250 tokens
-- Other
(900008,24,910201,0,0,2984),  -- Customization Potion, 150 tokens
(900008,25,910200,0,0,2984),  -- Faction Change Potion, 150 tokens
(900008,26,200001,0,0,2984);  -- Race Change Potion, 150 tokens

-- Stones of Retreat, all at 350 tokens, in a list of their own.
INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`)
SELECT 900010, 0, `entry`, 0, 0, 3015
  FROM `item_template`
 WHERE `name` LIKE 'Stone of Retreat%';

-- Lost caches: one per vanity category, 100 tokens each.
INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`) VALUES
(900009,0,8950001,0,0,2983),  -- Lost Weapon Cache
(900009,0,8950002,0,0,2983),  -- Lost Armor Cache
(900009,0,8950003,0,0,2983),  -- Lost Mount Cache
(900009,0,8950004,0,0,2983),  -- Lost Spell Cache
(900009,0,8950005,0,0,2983),  -- Lost Pet Cache
(900009,0,8950006,0,0,2983),  -- Lost Beast Cache
(900009,0,8950007,0,0,2983),  -- Lost Convenience Cache
(900009,0,8950008,0,0,2983),  -- Lost Curio Cache
(900009,0,8950009,0,0,2983);  -- Lost Toy Cache

-- Heirlooms: 39 items at 500 tokens each.
INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`) VALUES
-- Caches
(900011,0,1339058,0,0,3016),  -- Heirloom Cache 1339058
(900011,1,1339059,0,0,3016),  -- Heirloom Cache 1339059
(900011,2,1339060,0,0,3016),  -- Heirloom Cache 1339060
(900011,3,1339061,0,0,3016),  -- Heirloom Cache 1339061
(900011,4,1339062,0,0,3016),  -- Heirloom Cache 1339062
(900011,5,1339063,0,0,3016),  -- Heirloom Cache 1339063
(900011,6,1339064,0,0,3016),  -- Heirloom Cache 1339064
-- Trinkets
(900011,7,1642992,0,0,3016),  -- Discerning Eye of the Beast
(900011,8,1644098,0,0,3016),  -- Inherited Insignia of the Alliance
(900011,9,1644097,0,0,3016),  -- Inherited Insignia of the Horde
(900011,10,1642991,0,0,3016),  -- Swift Hand of Justice
-- Weapons
(900011,11,1642999,0,0,3016),  -- Ancient Crossbow
(900011,12,1642944,0,0,3016),  -- Balanced Heartseeker
(900011,13,1644096,0,0,3016),  -- Battleworn Thrash Blade
(900011,14,1642943,0,0,3016),  -- Bloodied Arcanite Reaper
(900011,15,1642946,0,0,3016),  -- Charmed Ancient Bone Bow
(900011,16,1642948,0,0,3016),  -- Devout Aurastone Hammer
(900011,17,1642947,0,0,3016),  -- Dignified Headmaster's Charge
(900011,18,1644095,0,0,3016),  -- Grand Staff of Jordan
(900011,19,1644092,0,0,3016),  -- Reforged Truesilver Champion
(900011,20,1648718,0,0,3016),  -- Repurposed Lava Dredger
(900011,21,1518202,0,0,3016),  -- Rethreaded Left Bear Claw
(900011,22,1518203,0,0,3016),  -- Rethreaded Right Bear Claw
(900011,23,1644091,0,0,3016),  -- Sharpened Scarlet Kris
(900011,24,3142943,0,0,3016),  -- Sturdied Arcanite Spear
(900011,25,1644094,0,0,3016),  -- The Blessed Hammer of Grace
(900011,26,1642902,0,0,3016),  -- Thrown Axe of the Executioner
(900011,27,1644093,0,0,3016),  -- Upgraded Dwarven Hand Cannon
(900011,28,1642945,0,0,3016),  -- Venerable Dal'Rend's Sacred Charge
(900011,29,1648716,0,0,3016),  -- Venerable Mass of McGowan
(900011,30,1642846,0,0,3016),  -- Wand of the Forgotten Lich
-- Relics and off-hand
(900011,31,1642896,0,0,3016),  -- Druid Idol of Agility
(900011,32,1642897,0,0,3016),  -- Druid Idol of Spells
(900011,33,1642901,0,0,3016),  -- Paladin Libram of Healing
(900011,34,1642900,0,0,3016),  -- Paladin Libram of Strength
(900011,35,3148335,0,0,3016),  -- Polished Observer's Shield
(900011,36,1642898,0,0,3016),  -- Shaman Totem of Agility
(900011,37,1642899,0,0,3016),  -- Shaman Totem of Spells
(900011,38,3140350,0,0,3016);  -- Urn of Aspiring Light
