"""Gera relatorio em ingles dos talentos AUSENTES no codigo, somente das
classes jogaveis do client CoA — para compartilhar com a equipe de QA.

Saida: tools/ascension-ref/data/missing_talents_report.md (data/ ignorado).
"""
import glob
import gzip
import json
import os
import re
from collections import defaultdict

# ---- ids referenciados no codigo + SQL ----
ids = set()
paths = (glob.glob("modules/mod-ascension-compat/src/*.cpp")
         + glob.glob("modules/mod-ascension-compat/src/*.h")
         + glob.glob("data/sql/updates/pending_db_world/*.sql")
         + glob.glob("modules/mod-ascension-compat/data/sql/db-world/*.sql"))
for p in paths:
    with open(p, encoding="utf-8", errors="replace") as f:
        for m in re.finditer(r"\b(\d{6,7})\b", f.read()):
            ids.add(m.group(1))

with open("tools/ascension-ref/index/spells.json", encoding="utf-8") as f:
    idx = json.load(f)

# ---- talentos das classes do client CoA ----
CLIENT_CLASSES = {
    "Barbarian", "Witch Doctor", "Felsworn", "Witch Hunter",
    "Stormbringer", "Knight of Xoroth", "Guardian", "Templar",
    "Bloodmage", "Ranger", "Chronomancer", "Necromancer", "Pyromancer",
    "Cultist", "Starcaller", "Sun Cleric", "Tinker", "Venomancer",
    "Reaper", "Primalist", "Runemaster",
}
missing = {}
with gzip.open("tools/ascension-ref/data/exiles_talents.jsonl.gz",
               "rt", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        r = json.loads(line)
        k = r["key"].split("/")[0]
        if k.startswith("reborn-") or k in ("none", "general-general1"):
            continue
        for x in r.get("structure", {}).get("references", []):
            key = x.get("key", "")
            if x.get("type") == "spell" and int(key) >= 500000 \
                    and key not in ids:
                cls = r["name"].split("\u2014")[0].strip()
                if cls in CLIENT_CLASSES:
                    missing.setdefault(key, set()).add(r["name"])

# ---- lookup in-game do exiles (tooltip/detalhes) quando disponivel ----
def exiles_url(sid):
    return f"https://db.exil.es/spell/{sid}"


rows = []
for sid in sorted(missing, key=int):
    name = idx.get(sid, {}).get("name", "?")
    trees = sorted(missing[sid])
    cls = trees[0].split("\u2014")[0].strip()
    specs = [t.split("\u2014")[-1].strip() for t in trees]
    spec = ", ".join(specs) if any("\u2014" in t for t in trees) else "class-wide"
    rows.append((sid, name, cls, spec))

rows.sort(key=lambda r: (r[2], int(r[0])))

out = [
    "# Missing CoA talent implementations",
    "",
    "Generated by `tools/ascension-ref/missing_talents_en.py` — cross-referenced",
    "the talent trees on the Ascension DB mirror (db.exil.es data) against all",
    "spell IDs referenced in `mod-ascension-compat` source and world SQL.",
    "",
    "A talent below has **no reference to its spell ID anywhere in the module",
    "code or SQL data**, which strongly suggests the talent currently does",
    "nothing in-game. **Please test each one in-game to confirm before filing",
    "or implementing anything.**",
    "",
    "Suggested test: learn the talent on a level-appropriate character,",
    "trigger its condition (deal damage, take damage, cast, kill, etc.) and",
    "check whether the described effect happens at all.",
    "",
    f"Total: **{len(rows)} missing talents** across "
    f"{len({c for _, _, c, _ in rows})} classes.",
    "",
]
cur_cls = None
for sid, name, cls, spec in rows:
    if cls != cur_cls:
        out += [f"## {cls}", ""]
        cur_cls = cls
    out.append(f"- **{name}** (`{sid}`, tree: {spec}) — "
               f"reference: {exiles_url(sid)}")
out.append("")
out.append("---")
out.append("Talent data source: db.exil.es mirror packaged in "
           "`hertigservices/ascension-data` (`exiles_talents.jsonl.gz`).")

dest = os.path.join("tools", "ascension-ref", "data", "missing_talents_report.md")
with open(dest, "w", encoding="utf-8") as f:
    f.write("\n".join(out))
print(f"report: {dest}")
print(f"missing: {len(rows)}")
