services:
  ac-gameplay-test:
    image: acore/ac-wotlk-gameplay-test:${DOCKER_IMAGE_TAG:-master}
    build:
      context: apps/coa-gameplay-test/docker
      args:
        BASE_IMAGE: acore/ac-wotlk-worldserver:${DOCKER_IMAGE_TAG:-master}
        DOCKER_USER: ${DOCKER_USER:-acore}
    profiles: [tests]
    network_mode: "service:ac-database"
    init: true
    stop_grace_period: 15m
    working_dir: /azerothcore-src
    entrypoint: ["bash", "/azerothcore-src/apps/coa-gameplay-test/docker/entrypoint.sh"]
    env_file:
      ${DOCKER_AC_ENV_FILE:-conf/dist/env.ac}
    environment:
      AC_DATA_DIR: "/azerothcore/env/dist/data"
      AC_LOGIN_DATABASE_INFO: "127.0.0.1;3306;root;${DOCKER_DB_ROOT_PASSWORD:-password};acore_auth"
      AC_WORLD_DATABASE_INFO: "127.0.0.1;3306;root;${DOCKER_DB_ROOT_PASSWORD:-password};acore_world"
      AC_CHARACTER_DATABASE_INFO: "127.0.0.1;3306;root;${DOCKER_DB_ROOT_PASSWORD:-password};acore_characters"
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASSWORD:-password}
    volumes:
      - .:/azerothcore-src:ro
      - ${DOCKER_VOL_ETC:-./env/dist/etc}:/coa/source-etc:ro
      - ${DOCKER_VOL_DATA:-ac-client-data}:/azerothcore/env/dist/data:ro
      - ./.cache/coa-gameplay-tests:/results
    depends_on:
      ac-database:
        condition: service_healthy
