-- Generated by Tools/Generate-CoAProcChances.py; do not edit.
--
-- These CoA passives state their own proc chance in Spell.dbc - the value their tooltips render as
-- "$h%" - and `spell_proc` was overriding every one of them with 100, so they fired on every
-- qualifying event instead of the 5% to 90% their own records authorise. Where the passive grants
-- extra strikes or resets an ability's cooldown, that is the difference between a small expected
-- bonus and a permanent one.
--
-- Clearing the column defers to the client: SpellMgr::LoadSpellProcs sets Chance from
-- SpellInfo::ProcChance when neither Chance nor ProcsPerMinute is set, so the authored value is used
-- and keeps being used after a client patch. ProcsPerMinute and Cooldown are left alone - no client
-- table carries either, so they stay a measurement question.
--
-- 153 spells, from Spell.dbc SHA256 D3DD607291D2D6793F72C7B13537F94FD7748D40A79A326DB6A8B4CB2ED41068.
START TRANSACTION;
UPDATE `spell_proc` SET `Chance` = 0 WHERE `SpellId` IN (300278, 300300, 300313, 300369, 300480, 300490, 300855, 302548, 503680, 503681, 503707, 503851, 503856, 503960, 504375, 504406, 504742, 505202, 520007, 520277, 520539, 524620, 524642, 524694, 524932, 538441, 560091, 560200, 560207, 560254, 560264, 560281, 560320, 560539, 560630, 560639, 560648, 560785, 561022, 561336, 562029, 572367, 573034, 574354, 630868, 653211, 653281, 653303, 653386, 653410, 680497, 680538, 680663, 680975, 681242, 681329, 681376, 681480, 681488, 704264, 704610, 704741, 704800, 704920, 704971, 705534, 705815, 705844, 705871, 705925, 705993, 705998, 706018, 706030, 706035, 706230, 706239, 706245, 706271, 706325, 706370, 706502, 706590, 706637, 706804, 706821, 706911, 707233, 707391, 707403, 707483, 707629, 707640, 707764, 712468, 800214, 800394, 800443, 800463, 800510, 801065, 801123, 801128, 801143, 801782, 801899, 802068, 802295, 802603, 802604, 802605, 802935, 803035, 803037, 803082, 803126, 803210, 803339, 803524, 803887, 803888, 804024, 804047, 804141, 804192, 804345, 804404, 804620, 804629, 804822, 804981, 804987, 805098, 805110, 805245, 805356, 805439, 805505, 805606, 805647, 805731, 805775, 805776, 805777, 805778, 806058, 806603, 806629, 806699, 806736, 806758, 807450, 807904);
COMMIT;
