-- Soulbender (804004): "Significantly increases the Runic Power generated by Deathchaser."
-- Spell.dbc authors the talent as a passive (Attributes 0x401c0) whose single effect is aura 42
-- (proc trigger spell) with TriggerSpell 355463 and BasePoints 199 / DieSides 1; the payload 355463
-- is effect 30 (SPELL_EFFECT_ENERGIZE) with misc 6 = POWER_RUNIC_POWER and bp 99 / DieSides 1 ->
-- +100 Runic Power, targeted at the caster (tgtA 1 = TARGET_UNIT_CASTER, native
-- SelectImplicitCasterObjectTargets), so the RP lands on the Reaper.
-- The proc gate is mis-authored: Spell.dbc gives 804004 ProcFlags 4
-- (PROC_FLAG_DONE_MELEE_AUTO_ATTACK) only. Deathchaser (560428/560429/561032) is a MELEE SPELL
-- (DmgClass 2), and Unit::ProcSkillsAndAuras assigns melee spells
-- PROC_FLAG_DONE_SPELL_MELEE_DMG_CLASS (0x10) — never DONE_MELEE_AUTO_ATTACK, which only white
-- swings set. So the talent as authored fires on auto-attacks and NEVER on Deathchaser casts.
-- A spell_proc row extends the gate to 4|16 = 20, keeping the authored auto-attack behavior and
-- adding the tooltip's Deathchaser case; the DBC's own proc handling
-- (AuraEffect::HandleProcTriggerSpellAuraProc casting TriggerSpell 355463) does the rest natively.
-- Columns mirror the Ultra Instinct 704654 row (rev_20260920_48): SpellFamilyName 0 / all
-- SpellFamilyMask 0 (no ability list — "Deathchaser" is the proc SOURCE, not a spellmod target),
-- SpellTypeMask 1 (PROC_SPELL_TYPE_DAMAGE — Deathchaser deals damage), SpellPhaseMask 2
-- (PROC_SPELL_PHASE_HIT), HitMask 0 (any hit — the tooltip names no crit condition), Chance 100
-- (the record's own ProcChance).
DELETE FROM `spell_proc` WHERE `SpellId` = 804004;
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(804004, 0, 0, 0, 0, 0, 20, 1, 2, 0, 0, 0, 0, 100, 0, 0);
