-- Constant Recovery (555729): "Reduces the threat generated by your holy spells by $s1% and healing done
-- by Reverse Wound now increases all healing taken the target receives by $680843s1% for $680843d."
-- The first clause is effect 0 (aura 10 SPELL_AURA_MOD_THREAT, EffectMiscValue 2 = school mask Holy,
-- EffectBasePoints -21 => -20%), handled natively by AuraEffect::HandleModThreat - untouched here.
-- The second clause is effect 1, aura 42 (proc trigger spell) on Recovering 680843 (aura 118
-- SPELL_AURA_MOD_HEALING_PCT, EffectBasePoints 5 => +6%, DurationIndex 1 = 10000 ms, implicit target 21
-- TARGET_UNIT_TARGET_ALLY). Spell.dbc gives 555729's record ProcFlags 0 and no `spell_proc` row existed,
-- so SpellMgr's generation pass skipped it and Aura::GetProcEffectMask returned 0: Recovering never
-- landed. AuraEffect::HandleProcTriggerSpellAuraProc sets the trigger target to the proc event's action
-- target, so once the proc exists the buff lands on the healed ally as the tooltip states.
-- Proc on the heal done by Reverse Wound 801303 (family 28, word1 0x20000 = 131072 and word2 0x1 = 1 -
-- its own SpellFamilyFlags; SpellInfo::IsAffected ORs across the three mask words). Reverse Wound is
-- SPELL_DAMAGE_CLASS_MAGIC and its SPELL_EFFECT_HEAL makes the cast positive, so
-- Spell::DoAllEffectOnTarget fills PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_POS (16384), and
-- Unit::ProcSkillsAndAuras sees a HealInfo with a nonzero heal and computes SpellTypeMask as
-- PROC_SPELL_TYPE_HEAL (2). SpellPhaseMask 2 (PROC_SPELL_PHASE_HIT). Chance is the record's own
-- ProcChance (100 - always, as the tooltip states no percentage). DisableEffectsMask 1 keeps the
-- MOD_THREAT effect out of the proc effect mask so the always-on threat reduction is never treated as a
-- proc effect.
DELETE FROM `spell_proc` WHERE `SpellId` = 555729;
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(555729, 0, 28, 0, 131072, 1, 16384, 2, 2, 0, 0, 1, 0, 100, 0, 0);
