-- Generated by tools/Generate-GuardianProcs.py; source only.
DELETE FROM `spell_proc` WHERE `SpellId` IN (504531, 570713, 582937, 704322, 802295, 804047);
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(704322, 0, 0, 0, 0, 0, 332118, 1, 2, 0, 0, 0, 0, 100, 0, 0),
(504531, 0, 0, 0, 0, 0, 20, 1, 2, 0, 0, 0, 0, 100, 0, 0),
(570713, 0, 0, 0, 0, 0, 20, 1, 2, 0, 0, 0, 0, 100, 0, 0),
(582937, 0, 0, 0, 0, 0, 16, 1, 2, 2, 0, 0, 0, 100, 0, 0),
(802295, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 20, 0, 0),
(804047, 0, 24, 0, 0, 4104, 16, 7, 4, 12287, 0, 0, 0, 20, 0, 0);
DELETE FROM `spell_script_names` WHERE `spell_id` = 704322 AND `ScriptName` = 'aura_ascension_guardian_favor_gain';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (704322, 'aura_ascension_guardian_favor_gain');

-- Mask audit (2026-09-22): 804047's mask (0, 0, 4104) was measured with mask_group.py and counted in
-- distinct abilities, not carriers - 20 carriers resolve to exactly 3 abilities (Ballad of the
-- Dragonslayer, Ballad of the Conqueror, Lesser Ballad of the Dragonslayer) and the tooltip names the
-- whole family ("Casting a Ballad"). Measured clean, no change.
