int main()
{
    Map map, otherMap;
    Player owner, ally, stranger;
    owner.guid = {1};
    ally.guid = {2};
    stranger.guid = {3};
    owner.cls = CLASS_RANGER;
    owner.map = ally.map = stranger.map = &map;
    owner.auras[92117] = {92117, owner.guid};
    owner.auras[707534] = {707534, owner.guid};
    spell_ascension_ranger_green_flower summon;
    summon.caster = &owner;
    summon.info.Id = 561005;
    summon.info.duration = 10000;
    assert(summon.Load());
    summon.Summon(0);
    assert(owner.creatures.empty());
    WorldLocation destination{6, 0, 0, 0};
    summon.fixtureDestination = &destination;
    owner.failSummon = true;
    summon.Summon(0);
    assert(!owner.HasAura(707539));
    owner.failSummon = false;
    summon.Summon(0);
    auto flower = owner.creatures.back().get();
    assert(flower->entry == 454239 && flower->motion.idle && flower->position == destination);
    assert(flower->duration == 10000 && flower->createdBy == 561005 && flower->ownerGuid == owner.guid);
    assert(flower->casts == std::vector<uint32>{561006});
    assert(owner.GetAura(707539, owner.guid)->stacks == 1);
    summon.Summon(0);
    assert(owner.GetAura(707539, owner.guid)->stacks == 2 && !flower->removed);
    summon.Summon(0);
    assert(!owner.HasAura(707539) && owner.HasAura(712427, owner.guid));
    owner.auras.erase(707534);
    summon.Summon(0);
    assert(!owner.HasAura(707539));
    owner.auras[707534] = {707534, owner.guid};
    spell_ascension_ranger_flower_pickup pickup;
    pickup.caster = flower;
    owner.position = {8, 0, 0, 0};
    ally.position = {6.5f, 0, 0, 0};
    stranger.position = {6.1f, 0, 0, 0};
    stranger.raid = false;
    auto anotherFlower = owner.creatures.back().get();
    std::list<WorldObject*> targets{&stranger, flower, anotherFlower, &owner, &ally};
    pickup.SelectAlly(targets);
    assert(targets == std::list<WorldObject*>{&ally});
    anotherFlower->entry = 454240;
    targets = {anotherFlower, &ally};
    pickup.SelectAlly(targets);
    assert(targets == std::list<WorldObject*>{&ally});
    anotherFlower->entry = 454239;
    ally.los = false;
    targets = {&ally, &owner};
    pickup.SelectAlly(targets);
    assert(targets == std::list<WorldObject*>{&owner});
    ally.los = true;
    ally.position = owner.position;
    targets = {&ally, &owner};
    pickup.SelectAlly(targets);
    assert(targets == std::list<WorldObject*>{&owner});
    owner.alive = false;
    targets = {&ally};
    pickup.SelectAlly(targets);
    assert(targets.empty());
    flower->ai->UpdateAI(500);
    assert(flower->removed);
    owner.alive = true;
    summon.Summon(0);
    flower = owner.creatures.back().get();
    owner.map = &otherMap;
    flower->ai->UpdateAI(500);
    assert(flower->removed);
    owner.map = &map;
    aura_ascension_ranger_dream_flowers proc;
    proc.target = &owner;
    DamageInfo damage;
    ProcEventInfo event{&owner, &stranger, &damage};
    stranger.friendly = false;
    assert(proc.CheckProc(event));
    event.hit = 0;
    assert(!proc.CheckProc(event));
    event.hit = PROC_HIT_CRITICAL;
    damage.amount = 0;
    assert(!proc.CheckProc(event));
    damage.amount = 1;
    event.actor = &ally;
    assert(!proc.CheckProc(event));
    event.actor = &owner;
    proc.Spawn(nullptr, event);
    assert(proc.prevented && owner.casts.back() == 561005);
    Spell cast;
    SpellInfo info;
    info.SpellFamilyName = 27;
    info.SpellFamilyFlags[0] = 32768;
    manager.spells[800150].ProcChance = 20;
    owner.auras[800150] = {800150, owner.guid};
    ranger_flower_casts casts;
    auto count = owner.casts.size();
    owner.combat = false;
    casts.OnSpellCast(&cast, &owner, &info, false);
    owner.combat = true;
    chancePass = false;
    casts.OnSpellCast(&cast, &owner, &info, false);
    assert(owner.casts.size() == count);
    chancePass = true;
    casts.OnSpellCast(&cast, &owner, &info, false);
    assert(owner.casts.size() == ++count);
    info.SpellFamilyFlags[0] = 0;
    info.CasterAuraSpell = 804329;
    casts.OnSpellCast(&cast, &owner, &info, false);
    assert(owner.casts.size() == ++count);
    cast.triggered = true;
    casts.OnSpellCast(&cast, &owner, &info, false);
    cast.triggered = false;
    info.CasterAuraSpell = 0;
    casts.OnSpellCast(&cast, &owner, &info, false);
    assert(owner.casts.size() == count);
    spell_ascension_ranger_highlander highlander;
    highlander.caster = &owner;
    highlander.fixtureTarget = &stranger;
    highlander.Snapshot();
    highlander.Consume();
    assert(!owner.HasAura(712427));
    highlander.Hit();
    assert(owner.casts.back() == 712428);
    count = owner.casts.size();
    highlander.Hit();
    assert(owner.casts.size() == count);
    owner.auras[707539] = {707539, owner.guid};
    owner.auras[712427] = {712427, owner.guid};
    owner.auras.erase(707534);
    ranger_highlander_cleanup cleanup;
    cleanup.OnPlayerUpdate(&owner, 1);
    assert(!owner.HasAura(707539) && !owner.HasAura(712427));
    ranger_flower_metadata metadata;
    info.Effects[0].Effect = SPELL_EFFECT_SUMMON;
    info.Effects[0].MiscValue = 454239;
    info.Effects[2].Effect = SPELL_EFFECT_TRIGGER_SPELL;
    info.Effects[2].TriggerSpell = 707539;
    metadata.OnLoadSpellCustomAttr(&info);
    assert(info.Effects[2].Effect == 0);
    info.Id = 712428;
    info.StackAmount = 4;
    metadata.OnLoadSpellCustomAttr(&info);
    assert(info.StackAmount == 1);
    owner.cls = CLASS_MAGE;
    assert(!summon.Load() && !highlander.Load() && !proc.CheckProc(event));
}
