-- Generated by worldforged-werkzeug/sql_bauen.py. Do not edit by hand.
--
-- The Worldforged upgrade recipes, rebuilt from the client's own data: the
-- family of an upgrade is stored in ItemAddon.dbc, where column f40 of the
-- upgraded variant points at its base item. 1738 first-rank upgrades survive
-- that way, 651 weapons and 1087 pieces of armour, and every base and target
-- row already exists in item_template.
--
-- The cost is NOT recovered. No captured store response survives and no
-- ItemExtendedCost row names a Worldforged base item. The numbers are computed
-- from Blizzard's own slot weights, so the progression follows a known logic
-- rather than an invented one. Replace the column and nothing else changes.

-- 1738 recipes: 651 weapons, 1087 armour.
DELETE FROM `worldforged_upgrade`;
INSERT INTO `worldforged_upgrade` (`store`,`base_item`,`target_item`,`cost`) VALUES
(8,202555,1378061,5000),  -- Rusty Blunderbuss
(8,217851,1379880,3926),  -- Junglewood Recurve
(9,217860,1379881,5234),  -- Shadow Cowl
(8,278843,1378062,3926),  -- Flesh Flayer Hook
(9,278844,1378063,2944),  -- Andorhal Manual
(8,278845,1378064,5234),  -- Reliever's Burden
(9,278846,1378065,5234),  -- Plague Mask
(9,278847,1378066,3926),  -- Libram of Remembrance
(9,278848,1378067,2944),  -- Blightbloom Talisman
(9,278849,1378068,2944),  -- Wraithbone Ring
(9,278850,1378069,3926),  -- Lost Scout's Idol
(8,278851,1378070,3926),  -- Skeletal Club
(9,278852,1378071,3926),  -- Infantry Gauntlets
(9,278853,1378072,2944),  -- Manacles of Eternal Shadow
(8,354059,1378074,5000),  -- Prodigy's Staff
(8,354060,1378075,5000),  -- Tarothae's Vow
(9,354062,1378077,2812),  -- Travel Cloak
(9,354063,1378078,2812),  -- Bottle of Endless Melon Juice
(9,354064,1378079,2812),  -- Cloak of Owlkin Feathers
(9,354065,1378080,2812),  -- Lost Rangari Ring
(9,354066,1378081,5000),  -- Crystalline Crown
(8,354067,1378082,3750),  -- Exodar Fragment
(9,354068,1378083,3750),  -- Totem of the Vale
(8,354069,1378084,3750),  -- Scourgewarped Bow
(9,354071,1378085,2812),  -- Faded Ward of the East Sanctum
(9,354072,1388074,2637),  -- Vial of Desolate Waters
(9,354076,1378090,2812),  -- Fundamentals of Arcana - Third Edition
(9,354077,1378091,2812),  -- Everyday Applications of Pyromancy
(9,354078,1378092,2812),  -- Principles of Cryomancy - Ultimate Edition, Version 2
(8,354083,1378094,5000),  -- Coil of Ula-Tek
(8,354084,1378095,3750),  -- Fang of Ula-Tek
(9,354085,1378096,2812),  -- Serpentbane Ring
(8,354086,1378097,3750),  -- Arkonite Saber
(9,354087,1378098,2812),  -- Arkonite Amulet
(9,354088,1378099,2812),  -- Blessed Arkonite Torch
(9,354089,1378100,3750),  -- Cowlen's Lost Gloves
(9,354090,1378101,2812),  -- Stillpine Cloak
(8,354091,1378102,5000),  -- Staff of Sciani
(9,354092,1378103,2812),  -- Fishbone Band
(8,354093,1378104,3750),  -- Ravager Quill
(9,354095,1378105,5000),  -- Tempered Mail
(9,354096,1378106,2812),  -- Light of the Highborne
(9,354098,1378108,2812),  -- Sigil of the Unmarked Mausoleum
(8,354099,1378109,3750),  -- Obsidian Smithing Hammer
(9,354100,1378110,2812),  -- Shield of Fading Light
(9,354101,1378111,2812),  -- Silkwrapped Cloak
(9,354102,1378112,2812),  -- Bloodweave Bindings
(8,354103,1378113,5000),  -- Sil'Vedore
(9,354104,1378114,5000),  -- Blessed Robes
(9,354105,1378115,2812),  -- Offering to Oocto
(9,354107,1378116,2812),  -- Stolen Highborne Bracelet
(9,354108,1378117,3750),  -- Boots of the Wilderness
(9,354109,1378118,2812),  -- Cryostasis Heart
(8,354110,1378119,5000),  -- Bloodcrystal Branch
(9,354111,1378120,5000),  -- Voidweaver Robes
(9,354112,1378121,2812),  -- Web Wrappings
(9,354113,1378122,5000),  -- Axxarien Kilt
(9,354114,1378123,2812),  -- Shield of the Royal Guard
(9,354116,1378125,2812),  -- Bloodcursed Ring
(9,354117,1378126,2812),  -- Veridian Eye
(9,354118,1378127,5000),  -- Ritualistic Nazzivien Headdress
(8,354120,1378129,3750),  -- Vector Rifle
(8,354121,1378130,3750),  -- Bloodwater
(9,354122,1378131,3750),  -- Vindicator's Shoulderguards
(9,354123,1378132,3750),  -- Ravager Trainer's Spaulders
(9,354124,1378133,5000),  -- Veridian Scale Mail
(9,354125,1378134,3750),  -- Warp Engineer's Boots
(9,354126,1378135,3750),  -- Bloodwashed Gloves
(9,354127,1378136,2812),  -- Flower of Tranquility
(8,354128,1378137,5000),  -- Staff of Talons
(8,354130,1378138,3750),  -- Venture Co. Logging Axe
(9,354131,1378139,5000),  -- Ziz's Alchemy Goggles
(9,354132,1378140,2812),  -- Light of the Talondeep Path
(9,354133,1378141,3750),  -- Grim Sorcerer Totem
(9,354134,1378142,2812),  -- Resonite Band
(8,354135,1378143,5000),  -- Barrel Smasher
(8,354136,1378144,3750),  -- Venture Co. Union Buster
(9,354137,1378145,3750),  -- Woven Ceremonial Belt
(8,354139,1378147,5000),  -- Fire Strike
(9,354140,1378148,2812),  -- Bloodfury Feather Cloak
(8,354141,1378149,5000),  -- Wind Shearer
(9,354142,1378150,5000),  -- Breastplate of the Current
(9,354143,1378151,3750),  -- Boulder Greaves
(9,354144,1378152,2812),  -- Vengeful Heart
(9,354146,1378153,2944),  -- Crimson Dragonscale
(9,354147,1378154,2812),  -- Balgaras's Foul Amulet
(9,354148,1378155,3750),  -- Wyrmscale Spaulders
(9,354151,1378158,5000),  -- Cursed Legguards of the Intrepid
(9,354152,1378159,2812),  -- Cursed Cape of the Wave Mistress
(9,354153,1378160,5000),  -- Mossy Hide Armor
(9,354154,1378161,2812),  -- Chewed Wrappings
(9,354158,1378163,2812),  -- Arkonite Orb
(9,354159,1378164,3750),  -- Abandoned Boots
(9,354160,1378165,3750),  -- Shoulderpads of the Conjuror
(8,354161,1378166,3750),  -- Flamescoured Bow
(9,354162,1378167,3750),  -- Burning Gauntlets
(9,354163,1378168,5000),  -- Ritual Robes
(8,354164,1378169,5000),  -- Blade of Thunder
(9,354167,1378172,3750),  -- Hatefury Skull Totem
(8,354168,1378173,3750),  -- Hatefury Wand
(8,354169,1378174,5000),  -- Spear of Hatred
(9,354170,1378175,5000),  -- Circlet of Desolation
(8,354171,1378176,3750),  -- Blade of Dread
(9,354172,1378177,2812),  -- Woven Flowers
(9,354173,1378178,5000),  -- Caravan Guard Vest
(9,354174,1378179,3750),  -- Caravan Guard Pauldrons
(9,354175,1378180,2812),  -- Sorrow of the Kodo
(8,354176,1378181,5000),  -- Bone Splitter
(9,354177,1378182,2812),  -- Offering to Azshara
(9,354178,1378183,5000),  -- Water Seer's Headdress
(9,354179,1378184,3750),  -- Diving Boots
(8,354180,1378185,3750),  -- Zelyn'Theris
(9,354181,1378186,5000),  -- Lost Mariner Leggings
(9,354182,1378187,2812),  -- Lost Mariner Bracers
(9,354183,1378188,2812),  -- Orb of Dawn
(9,354184,1378189,2812),  -- Kodo Hide Cloak
(8,354185,1378190,3750),  -- Burning Blade Ritual Knife
(9,354186,1378191,3750),  -- Heretical Libram
(8,354187,1378192,5000),  -- Doomwarden
(9,354188,1378193,5000),  -- Pillaged Legguards
(8,354189,1378194,3750),  -- Gelkis Cleaver
(8,354190,1378195,3750),  -- Shell Cracker
(9,354191,1378196,2812),  -- Sunken Ring
(9,354192,1378197,3750),  -- Gloves of Patience
(9,354193,1378198,2812),  -- The Undying Eye
(8,354194,1378199,3750),  -- Magram Hatchet
(9,354195,1378200,5000),  -- Crown of the Great Khan
(8,354196,1378201,5000),  -- Jairal'Kesh, Staff of Summoning
(8,354197,1378202,3750),  -- Shadowbreaker
(8,354198,1378203,3750),  -- Kodo Hunter
(8,354199,1378204,3750),  -- The Winning Javelin
(8,354200,1378205,5000),  -- Bone Harvester
(9,354201,1378206,2812),  -- Buried Bracers
(8,354202,1378207,3750),  -- Stormpiercer
(9,354203,1378208,5000),  -- Maraudine Breastplate
(9,354204,1378209,2812),  -- Maraudine Cape
(9,354205,1378210,3750),  -- Maraudine Gloves
(9,354206,1378211,2812),  -- Icon of Khan Maraudos
(9,354207,1378212,2812),  -- Ambereye Amulet
(8,354208,1378213,5000),  -- Greataxe of Kolk
(9,354209,1378214,2812),  -- Shadowshard Shield
(9,354210,1378215,2812),  -- Ring of Arakosh
(9,354211,1378216,2812),  -- Ring of Korvaix
(9,354212,1378217,5000),  -- Antique Alteraci Skirt
(8,354213,1378218,5000),  -- Alteraci Avenger
(8,354214,1378219,3750),  -- Embrace of the Fifth
(9,354215,1378220,2812),  -- Crushridge Fingerguards
(9,354216,1378221,5000),  -- Battleplate of Crimson Resolve
(8,354217,1378222,3750),  -- Syndicate Chopping Axe
(9,354218,1378223,3750),  -- Libram of the Third Host
(8,354219,1378224,3750),  -- Sentry Shot
(8,354220,1378225,5000),  -- Staff of Argus
(8,354221,1378226,3750),  -- Icecracker
(8,354222,1378227,5000),  -- Ogre Toothpick
(9,354223,1378228,2812),  -- Frozen Alterac Banner
(8,354224,1378229,3750),  -- Frostwatch Defender
(9,354225,1378230,3750),  -- Tempered Syndicate Boots
(8,354226,1378231,5000),  -- Dandred's Harvester
(9,354228,1378232,2812),  -- Cape of the Mire
(9,354229,1378233,5000),  -- Fallow Tunic
(9,354230,1378234,3750),  -- Kreil's Gauntlets
(9,354231,1378235,2812),  -- Sorrow's Light
(9,354232,1378236,5000),  -- Grave Leggings
(9,354233,1378237,2812),  -- Holy Atal'ai Band
(8,354234,1378238,5000),  -- Spear of Emerald
(9,354235,1378239,2812),  -- Icon of Blood
(9,354236,1378240,2812),  -- Defiled Necklace
(8,354237,1378241,5000),  -- Dragoncarver
(8,354238,1378242,3750),  -- Sharpened Dragon Bone
(9,354239,1378243,3750),  -- Pauldrons of the Ancient Prophet
(9,354240,1378244,5234),  -- Kazkaz's Ceremonial Mask
(9,354241,1378245,3926),  -- Atal'ai Alchemy Gloves
(8,354242,1378246,5000),  -- Sha-Bane Staff
(9,354243,1378247,3750),  -- Splinterspear Belt
(9,354244,1378248,2812),  -- Itharius's Bracers
(9,354245,1378249,5000),  -- Biggs's Spare Legguards
(9,354246,1378250,3750),  -- Atal'ai Angler Boots
(9,354247,1378251,2812),  -- Emerald Tear
(9,354248,1378252,3750),  -- Idol to Hakkar
(8,354250,1378254,3750),  -- Sawtooth Jaw
(9,354251,1378255,2812),  -- Signet of Lire'kes
(9,354252,1378256,2812),  -- Bracers of Emerald Will
(8,354253,1378257,3750),  -- Swamp Talker's Crossbow
(8,354254,1378258,3750),  -- Marsh Bonebreaker
(9,354255,1378259,2812),  -- Cartographer's Cape
(9,354256,1378260,2812),  -- Exile's Amulet
(9,354257,1378261,2812),  -- Dusksinger Band
(9,354258,1378262,2812),  -- Choker of Hakkar
(9,354259,1378263,5000),  -- Murloc Crown
(9,354260,1378264,2812),  -- Rusted Shield
(9,354261,1378265,3750),  -- Marsh Adventurer Boots
(9,354262,1378266,3750),  -- Unusual Emerald Scales
(9,354263,1378267,5000),  -- Robe of Woven Dreams
(9,354264,1378268,2812),  -- Scout's Bracers
(9,354265,1378269,2812),  -- Giant Ruby Eye
(8,354266,1378270,3750),  -- The Wanderer's Stirring Rod
(8,354269,1378272,5000),  -- Woodcleaving Axe
(9,354271,1378273,2812),  -- Drape of the Lost
(8,354273,1378274,3750),  -- Vigilant Glaive
(8,354274,1378275,5234),  -- Bag of Folding
(9,354275,1378276,2944),  -- On the Importance of Arcane Foci
(9,354276,1378277,5234),  -- Bear's Head Apprentice Robe
(9,354277,1378278,3926),  -- Totem of Venc
(9,354278,1378279,5234),  -- Legashi Hellmail
(9,354279,1378280,3926),  -- Kim'Jael's "Trustworthy" Boots
(8,354283,1378282,3926),  -- Vuna'thell
(8,354300,1378288,5000),  -- Hexed Staff
(9,354325,1378290,2944),  -- Torn Cloak
(8,354326,1378291,3926),  -- Hive Regal Claw
(9,354327,1378292,2812),  -- Hercular's Unstable Orb
(9,354328,1378293,5234),  -- Burning Vanguard Hauberk
(9,354446,1378294,2944),  -- Bastion of the Fallen
(9,354447,1378295,2944),  -- Faded Promise Ring
(9,354448,1378296,2944),  -- Veneration to the Ancient Ones
(8,354449,1378297,5234),  -- Axe of Slaughter
(9,354450,1378298,3926),  -- Bloodied Gauntlets
(9,354451,1378299,5234),  -- Vulture Hide Leggings
(8,354452,1378300,5000),  -- Betrayal's Edge
(9,354453,1378301,2944),  -- Banner of the Dark Riders
(9,354454,1378302,2944),  -- Reverence of the Ancient Ones
(8,354455,1378303,3926),  -- Kire, Exaltation of the Ancient Ones
(9,354456,1378304,3926),  -- Girdle of the Shadowslayer
(9,354457,1378305,5234),  -- Ariden's Circlet
(8,354458,1378306,5234),  -- Branch of Mourning
(9,354459,1378307,2944),  -- Aion of Desolation
(9,354460,1378308,3926),  -- Pauldrons of Shadow
(9,354461,1378309,5234),  -- Celsalia's Luxorious Robes
(8,354462,1378310,3926),  -- Shorean's Ironwood Longbow
(9,354463,1378311,3926),  -- Ashen Boots
(8,354464,1378312,3926),  -- Volkmar's Enchanting Rod
(8,354465,1378313,3926),  -- The Master's Bottle
(9,354466,1378314,2944),  -- Vintner's Wristguards
(9,354469,1378317,2944),  -- Fragment of K'aresh
(8,354473,1378320,5000),  -- Slayer's Claymore
(9,354474,1378321,3750),  -- Cord of Reverence
(9,354475,1378322,2812),  -- Aloof Tauren's Herbs
(9,354476,1378323,2812),  -- Bones to Munch
(9,354477,1378324,2812),  -- Lookout Scope
(8,354478,1378325,3750),  -- Goldenmist Waterblade
(9,354479,1378326,3750),  -- Earth Reverent's Sash
(8,354480,1378327,5000),  -- Staff of the Wind Sisters
(8,354481,1378328,3750),  -- Needlewind Crossbow
(9,354482,1378329,3750),  -- Engine Safety Belt
(9,354483,1378330,3750),  -- Freewind Gloves
(9,354485,1378331,3750),  -- Warcaster Slippers
(9,354486,1378332,3750),  -- Dustscour Courier Belt
(9,354487,1378333,2812),  -- Alteraci Band
(9,354488,1378334,2812),  -- Shredder's Medallion
(8,354489,1378335,3750),  -- Syndicate Crossbow
(8,354490,1378336,5000),  -- Tombbound Warhammer
(9,354491,1378337,3750),  -- Bloodscalp Cord
(9,354492,1378338,3750),  -- Tinkering Belt
(9,354493,1378339,2812),  -- Sky Shot Cloak
(8,354494,1378340,3750),  -- Bloodsail Longbow
(8,354495,1378341,3750),  -- Grom'gol Hunting Rifle
(8,354497,1378342,5000),  -- Wind Ritual Staff
(8,354498,1378343,3750),  -- Axe of the Lost
(8,354499,1378344,5000),  -- Nightmare's Edge
(8,354500,1378345,3750),  -- Khazno's Shotgun
(8,354501,1378346,3750),  -- Crocolisk Hunter's Bow
(8,354502,1378347,3750),  -- Wand of the Ancients
(8,354503,1378348,5000),  -- Sandworn Arcanist Staff
(9,354504,1378349,3750),  -- Duststorm Sash
(9,354505,1378350,5000),  -- Cracked Earth Vest
(9,354506,1378351,3750),  -- Planned Strike Cord
(9,354507,1378352,2812),  -- Quel'Danil Amulet
(9,354509,1378353,3750),  -- Sash of Contemplation
(9,354510,1378354,3750),  -- Ancient Vilebranch Gloves
(9,354511,1378355,2812),  -- Nightmarish Bracers
(9,354512,1378356,3750),  -- Fractured Shoulderpads
(8,354513,1378357,3750),  -- Wand of the Sands
(9,354514,1378358,3926),  -- Belt of the Shen'dralar
(9,354515,1378359,5000),  -- Beezil's Pants
(9,354516,1378360,3750),  -- Drywallow Gloves
(9,354517,1378361,3750),  -- Inscribed Sash
(9,354518,1378362,3750),  -- Theramore Girdle
(9,354519,1378363,3750),  -- Burnt Spaulders
(9,354521,1378364,5000),  -- Old Theramore Guard Plate
(8,354522,1378365,3750),  -- Draenic Longbow
(8,354523,1378366,3926),  -- Felshot
(9,410010,1378367,2944),  -- Phylactery Shard
(8,410012,1378369,5234),  -- Shimmering Scarlet Cane
(9,410013,1378370,5234),  -- Scarlet Overalls
(8,410014,1378371,3926),  -- Scarlet Slicer
(8,410016,1378373,3750),  -- Northridge Hatchet
(9,410017,1378374,5234),  -- Bloodied Pants
(8,410018,1378375,5234),  -- Tracker's Plagued Spike
(8,410019,1378376,3926),  -- Sentinel Sharpshooter
(9,410020,1378377,3750),  -- Ebonblight Slippers
(8,410021,1378378,3926),  -- Burning Judgement
(9,410022,1378379,2944),  -- Scarlet Band
(9,410023,1378380,2944),  -- Scarlet Shield
(9,410024,1378381,2944),  -- Brightflame Codex
(9,410025,1378382,5234),  -- Scarlet Robe
(9,410026,1378383,3926),  -- Scarlet Pauldrons
(8,410027,1378384,5234),  -- Charred Slicer
(8,410028,1378385,5234),  -- Staff of the Twisted Spirit
(9,410029,1378386,3926),  -- Scourgestalker's Girdle
(8,410030,1378387,3926),  -- Bonescourge Dagger
(9,410031,1378388,3926),  -- Ghoul-Stitched Shoulders
(8,410032,1378389,3926),  -- Fetid Mace
(8,410033,1378390,3926),  -- Graveyard Striker
(9,410034,1378391,3926),  -- Decayed Grippers
(9,410035,1378392,2944),  -- Plagued Cloak
(9,410036,1378393,5234),  -- Apothecary Cowl
(9,410038,1378394,2944),  -- Bravecrest Chain
(9,410039,1378395,3926),  -- Dustsworn Sash
(8,410040,1378396,3926),  -- Excavator's Pick
(9,410041,1378397,2944),  -- The Eternal's Journal
(8,410042,1378398,3926),  -- Wand of Twilight
(9,410043,1378399,2944),  -- Twilight Talisman
(9,410044,1378400,5234),  -- Shadow Slinger Pants
(9,410045,1378401,3926),  -- Infested Pauldrons
(8,410046,1378402,3926),  -- Trigdy's Pistol
(8,410047,1378403,5234),  -- Standard Cenarion Spear
(9,410048,1378404,5234),  -- Ancient Sentinel Headdress
(8,410049,1378405,3926),  -- Southwind Defender
(9,410050,1378406,5234),  -- Runaway's Tunic
(8,410051,1378407,5234),  -- Darnell's Blade
(8,410052,1378408,5234),  -- Scarab Smasher
(9,410053,1378409,2944),  -- Horde Recruitment Insignia
(9,410054,1378410,2944),  -- Alliance Recruitment Badge
(8,410055,1378411,3926),  -- Twilight's Presence
(9,410056,1378412,2944),  -- Geo Band
(8,410057,1378413,3926),  -- Cursed Ritual Carver
(9,410058,1378414,2944),  -- Wind Pendant
(9,410059,1378415,5234),  -- Qiraji Scale Greaves
(9,410060,1378416,2944),  -- Chitin Thread Wraps
(9,410061,1378417,5234),  -- Silithic Scale Hauberk
(9,410062,1378418,3926),  -- Hardened Scarab Gauntlets
(9,410063,1378419,2944),  -- Soldier's Bulwark
(9,410064,1378420,5234),  -- Rockstalker Silk Robe
(9,410065,1378421,3926),  -- Idol of Shifting Sands
(8,410066,1378422,3926),  -- Sandreaver Longbow
(8,410067,1378423,5234),  -- Twilight Prophet Staff
(9,410068,1378424,3926),  -- Scorpionscale Mantle
(9,410069,1378425,3926),  -- Carapace Clasps
(8,410070,1378426,3926),  -- Lost Cenarion Bolter
(8,410071,1378427,3926),  -- Sandstone Sniper
(9,410072,1378428,2944),  -- Bracers of the Bound Storm
(9,410073,1378429,3926),  -- Old God Carving
(8,410074,1378430,3926),  -- Sandstorm Shaper
(8,410075,1378431,3750),  -- Brigade Blunderbuss
(9,410076,1378432,3926),  -- Purple Steppers
(8,410077,1378433,5234),  -- Chitinsunder Greataxe
(9,410079,1378434,3926),  -- Timbermaw Idol
(9,410080,1378435,2944),  -- Thermal Pendant
(9,410081,1378436,5234),  -- Researcher's Dish
(8,410082,1378437,5000),  -- Chillbane Cleaver
(9,410083,1378439,2944),  -- Winter Band
(9,410085,1378440,2944),  -- Winter's Last Embrace
(9,410086,1378441,5234),  -- Fur-Lined Vest
(9,410087,1378442,2944),  -- Excavator's Buckler
(9,410088,1378443,3926),  -- Windsong Totem
(9,410089,1378444,2944),  -- Glacierpaw Bindings
(9,410090,1378445,3926),  -- Flattened Shoulderpad
(8,410091,1378446,3926),  -- Snowtalon Crossbow
(8,410092,1378447,5234),  -- Icemaw Greatmaul
(8,410093,1378448,3926),  -- Aurorawhirl Pick
(8,410094,1378449,3926),  -- Frostglade Saber
(9,410095,1378450,2944),  -- Wailing Talisman
(9,410096,1378451,3926),  -- Lonely Gauntlets
(9,410097,1378452,2944),  -- Wintergale Cloak
(8,410098,1378453,3926),  -- Snowstalker Rifle
(8,410099,1378454,5234),  -- Frostsaber Halberd
(9,410100,1378455,3926),  -- Coldsnap Girdle
(9,410101,1378456,5234),  -- Owlbeast Pantaloons
(9,410102,1378457,2944),  -- Owlbeast Talon
(9,410103,1378458,5234),  -- Horror Horns
(9,410104,1378459,3926),  -- Non-Slip Winter Boots
(9,410105,1378460,5234),  -- Winterbite Legguards
(8,410106,1378461,3926),  -- Winterfall Dagger
(9,410107,1378462,2944),  -- Cold Wristguards
(8,410108,1378463,3750),  -- Chillhammer
(9,410109,1378465,2944),  -- Ice Thistle Cape
(8,410110,1378466,3926),  -- Hunter's Knife
(9,410111,1378467,2944),  -- Aurora Orb
(9,410112,1378468,3926),  -- Stormchill Spaulders
(8,410113,1378469,5234),  -- Azure Focusing Staff
(9,410114,1378470,2944),  -- Maddening Signet
(9,410115,1378471,3926),  -- Eversleet Handguards
(9,410116,1378472,5234),  -- Frostweave Vestment
(8,410117,1378473,3926),  -- Starfall Longbow
(8,410118,1378474,3926),  -- Ice Shaver
(8,410119,1378475,3926),  -- The Leaping Arc
(8,410121,1378477,5234),  -- Darkwhisper Spear
(8,410123,1378479,3926),  -- Hyjal Protector's Knuckleduster
(9,410124,1378480,3926),  -- Libram of Amphibious Devotion
(8,410125,1378481,5234),  -- Snowpeak Claymore
(8,410127,1378482,3926),  -- Cryptfiend Fang
(9,410128,1378483,5234),  -- Revival Garments
(9,410129,1378484,3926),  -- Argent Sentry Pauldrons
(8,410130,1378485,3926),  -- Fungal Cleaver
(9,410131,1378486,2944),  -- Forbidden Fruit
(9,410132,1378487,3926),  -- Mossflayer Lost Totem
(8,410133,1378488,3926),  -- Tainted Wasteblade
(9,410134,1378489,3926),  -- Resilient Stompers
(9,410135,1378490,3926),  -- Idol of Breathing Life
(8,410136,1378491,5234),  -- Deadcapitator
(9,410137,1378492,3926),  -- Scarlet Doctrine
(8,410138,1378493,3926),  -- Scarlet Crossbow
(8,410139,1378494,3926),  -- Scarlet Cauterizer
(8,410140,1378495,5234),  -- Scorched Runeblade
(8,410141,1378496,3926),  -- Malleus Haereticorum
(9,410142,1378497,3926),  -- Ghoulbane Gauntlets
(8,410143,1378498,3926),  -- The Silver Blade
(9,410144,1378499,2944),  -- Plague Purger
(9,410147,1378502,2944),  -- Bubbling Blood of Heroes
(9,410148,1378503,2944),  -- Ring of Memorial
(9,410149,1378504,2944),  -- Deathguard Vambraces
(9,410150,1378505,2944),  -- Cryptsilk Cuffs
(8,410151,1378506,3926),  -- Adon's Second Blade
(9,410152,1378507,5234),  -- Watchman Helm
(9,410153,1378508,2944),  -- Quel'thalas Commander Aegis
(8,410154,1378509,5234),  -- Plaguebloom Spear
(9,410155,1378510,2944),  -- Ghost-thread Shroud
(9,410156,1378511,3926),  -- Red Metal Pauldrons
(9,410157,1378512,5234),  -- Spiritwoven Vestments
(8,410158,1378513,3926),  -- Blight Bomber
(8,410160,1378515,5234),  -- Ghost Buster
(8,410161,1378516,3926),  -- Assisting Hand
(8,410162,1378517,5234),  -- Junior Mallet
(9,410163,1378518,5000),  -- Sorrow Leggings
(9,410164,1378519,3926),  -- Gravewood Belt
(9,410165,1378520,3926),  -- Plague Fiend Chain
(9,410166,1378521,2944),  -- Wailing Spirit Amulet
(9,410167,1378522,3926),  -- Ebonshadow Breeches
(9,410168,1378523,5234),  -- Havenfire Crown
(9,410169,1378524,5234),  -- Havenfire Crown
(8,410170,1378525,3926),  -- Ravenridge Shotgun
(9,410171,1378526,3926),  -- Bleakfang Handwraps
(8,410172,1378527,5234),  -- Gravecall Staff
(9,410173,1378528,2944),  -- Eboncrypt Band
(9,410174,1378529,2944),  -- Scourge Cloak
(8,410175,1378530,3926),  -- Deathwhisper Wand
(8,410176,1378531,5234),  -- Plagued Pitchfork
(9,410177,1378532,3926),  -- Shadowgrasp Sash
(8,410178,1378533,3926),  -- Borelgore's Chewtoy
(8,410179,1378534,3926),  -- Flamefist Claw
(9,410180,1378535,3926),  -- Darkflight Totem
(8,410181,1378536,3926),  -- Cinderstrike Mace
(9,410182,1378537,2944),  -- Ashfall Vambraces
(9,410183,1378538,3926),  -- Dark Iron Handwraps
(9,410184,1378539,5234),  -- Magmaweave Pantaloons
(8,410185,1378540,5234),  -- Flamescale Spire
(9,410186,1378541,3926),  -- Charfall Mantle
(9,410187,1378542,2944),  -- Firestorm Cloak
(9,410188,1378543,3926),  -- Red Chain Belt
(9,410189,1378544,2944),  -- Ancient Whetstone
(9,410190,1378545,2944),  -- Volcanic Aegis
(8,410191,1378546,3926),  -- Inferno Gavel
(8,410192,1378547,5234),  -- Smolderwing Decapitator
(9,410193,1378548,5234),  -- Madness Crown
(9,410194,1378549,2944),  -- Ashenpeak Band
(8,410195,1378550,3926),  -- Blackrock Side Blade
(8,410196,1378551,3926),  -- Blackrock Hatchet
(8,410197,1378552,5234),  -- Blackrock Pike
(9,410198,1378553,3926),  -- Emberstep Sabatons
(8,410199,1378554,3926),  -- Charblaze Rifle
(8,410200,1378555,5234),  -- Spiked Maul
(8,410201,1378556,3926),  -- Obsidian Boltthrower
(8,410202,1378557,5234),  -- The Final Strike
(9,410203,1378558,2944),  -- Grave Offering
(8,410204,1378559,3926),  -- Burnscorch Wand
(8,410205,1378560,3926),  -- Wyrmkin Shiv
(9,410207,1378562,5234),  -- Blisterhide Headguard
(8,410208,1378563,3926),  -- Ashendawn Bow
(8,410209,1378564,3926),  -- Lava Absorbing Blade
(9,410210,1378565,2944),  -- Firegut Emblem
(9,410211,1378566,2944),  -- Ashen Cape
(9,410212,1378567,2944),  -- Moltenflow Tome
(9,410213,1378568,2944),  -- Charred Signet
(9,410214,1378569,2944),  -- Embershard Choker
(9,410215,1378570,5234),  -- Flamescale Leggings
(9,410216,1378571,2944),  -- Blazing Ember
(9,410217,1378572,3926),  -- Smokeshell Gauntlets
(9,410218,1378573,3926),  -- Cinderthread Sash
(8,410219,1378574,5234),  -- Bloodspire Staff
(8,410220,1378575,3926),  -- Infernal Fang
(9,410221,1378576,5234),  -- Ashstone Robes
(9,410222,1378577,3926),  -- Moltengore Spaulders
(8,410223,1378578,5234),  -- Searsteel Claymore
(8,410224,1378579,3926),  -- Charbite Mace
(8,410225,1378580,5234),  -- Embercarve Greataxe
(8,410226,1378581,3926),  -- Blackbreach Handaxe
(9,410227,1378582,3926),  -- Lavasilk Footpads
(8,410228,1378583,3926),  -- Magma Poker
(9,410229,1378584,3926),  -- Firebrand Libram
(8,410230,1378585,3926),  -- Searwind Wand
(9,410231,1378586,5234),  -- Flayer's Helmet
(9,410232,1378587,3926),  -- Sticky Sabatons
(8,410233,1378588,3926),  -- Scarlet Blunderbuss
(9,410234,1378589,2944),  -- Skippy's Bone
(9,410235,1378590,2944),  -- Spiced Rum
(9,410238,1378591,2944),  -- Flame-Kissed Wraps
(9,415001,1378592,2812),  -- Stromgarde Spell Tome
(9,415002,1378593,2812),  -- Stromgarde Buckler
(8,415003,1378594,5000),  -- Caretaker's Burden
(8,415004,1378595,3750),  -- Peace of the Dead
(8,415005,1378596,3750),  -- Syndicate Shanker
(8,415006,1378597,3750),  -- Blade of the Syndicate Lord
(9,415007,1378598,3750),  -- Muffled Boots
(9,415008,1378599,2812),  -- Onestone's One Stone
(9,415009,1378600,5000),  -- Water Drawing Cap
(9,415010,1378601,2812),  -- Musty Horse Blanket
(8,415011,1378602,3750),  -- Syndiclap
(8,415012,1378603,3750),  -- Commode Cleaver
(8,415013,1378604,3750),  -- Witherbark Headsmasher
(9,415014,1378605,3750),  -- The Withered Totem
(9,415015,1378606,2812),  -- Rough Weathered Ring
(8,415016,1378607,3750),  -- Skullknocker
(8,415017,1378608,5000),  -- Heavy Tempered Blade
(9,415018,1378610,3750),  -- Withered Trollkin Shoulders
(8,415019,1378611,3750),  -- Poacher's Bow
(8,415020,1378612,3750),  -- Dark Iron Blaster
(8,415021,1378613,3750),  -- Ancient Dark Iron Mace
(9,415022,1378614,2812),  -- Stolen War Pendant
(9,415023,1378615,5000),  -- Forgotten Fitted Pants
(9,415024,1378616,2812),  -- Abandonded Wristguard
(9,415025,1378617,3750),  -- Interlinked Fingerguards
(9,415026,1378618,5000),  -- Watchguard's Prized Plate
(9,415027,1378619,2812),  -- Thunder Infused Offering
(9,415028,1378620,5000),  -- Suprisingly Sturdy Helm
(8,415029,1378621,5000),  -- Ancient Wavepiercer
(8,415030,1378622,5000),  -- Boarder's Axe
(9,415031,1378623,3750),  -- Circle of Waves Idol
(9,415032,1378624,2812),  -- Hammerfall Wristguards
(9,415033,1378625,5000),  -- Brumn's Unfinished Project
(9,415034,1378626,3750),  -- Deadweight Pauldrons
(9,415035,1378627,2812),  -- Versatile Fishing Blanket
(9,415036,1378628,2812),  -- Offering Pendant
(9,415037,1378629,3750),  -- Mountain Climbers
(8,415038,1378630,3750),  -- Plains Bolter
(9,415039,1378631,2812),  -- Earth Infused Offering
(9,415040,1378632,5000),  -- Loose Treasure Pants
(8,415041,1378633,3750),  -- Grave Spite
(8,415042,1378634,3750),  -- Arcane Impaler
(9,415043,1378635,3750),  -- Silken Travel Gloves
(9,415044,1378636,2812),  -- Flame Infused Offering Band
(9,415045,1378637,5000),  -- Mok'rash's Circlet
(8,415046,1378638,3750),  -- Hull Breaker
(8,415047,1378639,3750),  -- Keelhaul's Saber
(9,415048,1378640,3750),  -- Cannon Loaders
(9,415049,1378641,2812),  -- Tamas's Black Powder Pouch
(8,415050,1378642,3750),  -- Bloodsail Decksweeper
(9,415051,1378643,2812),  -- Gorilla Pelt
(9,415052,1378644,2812),  -- Blackwater Booty Band
(9,415054,1378646,2812),  -- Premium Banana
(9,415055,1378647,5000),  -- Pilfered Plate Pants
(9,415056,1378648,2812),  -- Zanzil Vial Pendant
(8,415057,1378649,3750),  -- Alchemist's Ladel
(8,415058,1378650,3750),  -- Sea Cleaver
(9,415059,1378651,2812),  -- Special Seashell
(8,415060,1378652,3750),  -- Buccaneer Shiv
(8,415061,1378653,5000),  -- Naga Throwing Trident
(9,415062,1378654,5000),  -- Jose's Best Slacks
(9,415063,1378655,2812),  -- Mangled Wraps
(9,415064,1378656,2812),  -- Sharpened Raptor Tooth
(9,415065,1378657,2812),  -- A Guide to a Succubus' Darkest Secrets
(9,415066,1378658,2812),  -- Pristine Tethis Feather
(9,415067,1378659,2812),  -- Ancient Sea-dweller Charm
(8,415068,1378660,5000),  -- Voodoo Bonemaker
(9,415069,1378661,5000),  -- South Sea Dress
(9,415070,1378662,3750),  -- Jungle Stalker Pauldrons
(8,415071,1378663,5000),  -- Hunting Spear
(8,415072,1378664,5000),  -- Mosh'Ogg Stave
(9,415073,1378665,2812),  -- Kal'ai Jewel
(9,415074,1378666,3750),  -- Ravaged Shoulderpads
(8,415075,1378667,3750),  -- Bloodscalper
(8,415076,1378668,3750),  -- Panther Shredders
(9,415077,1378669,5000),  -- Zul'Kunda Tribe Trophy
(9,415078,1378670,2812),  -- Wizard Cuffs
(9,415079,1378671,2812),  -- Yojamba Hex Skull
(9,415080,1378672,2812),  -- Depleted Elemental Lodestone
(9,415081,1378673,2812),  -- Zul'Kunda Blood Ring
(9,415082,1378674,2812),  -- Bloodscalp Beastmastery Amulet
(9,415083,1378675,5000),  -- Zul'Kunda Scout Vest
(8,415084,1378676,3750),  -- Bloodscalp Skullpiercer
(8,415085,1378677,5000),  -- Jungle Defender
(9,415087,1378678,3750),  -- Nesingwary Tracking Boots
(9,415088,1378679,2812),  -- Riverheart Crest
(9,415089,1378680,3750),  -- Last Guardian
(9,415090,1378681,2812),  -- Jungle Medicine Compendium
(8,415091,1378682,5000),  -- Jungle Broadblade
(8,415092,1378683,5000),  -- The Wrangler
(8,415093,1378684,3750),  -- Shiv of Warm Greetings
(9,415094,1378685,3750),  -- Witchdoctor Mixing Gloves
(8,415095,1378686,3750),  -- Kurzen Eviscerator
(8,415096,1378687,5000),  -- Kurzen Madness Blade
(9,415097,1378688,2812),  -- Crystallized Shield
(8,415098,1378689,3750),  -- Gurubashi Trainee Hatchet
(9,415099,1378690,3750),  -- Rebel Runners
(9,415100,1378691,3750),  -- Axe Swingers
(9,415101,1378692,5000),  -- Splinter Guard
(9,415102,1378693,2812),  -- Cogwheel Band
(9,415103,1378694,3750),  -- Mosh'Ogg Totem
(8,415104,1378695,3750),  -- Mind's Eye Fragment
(8,415105,1378696,5000),  -- Fifth Staff of Mosh'Ogg Magic Circle
(9,415106,1378697,2812),  -- Thunder Fur Cloak
(8,415107,1378698,3750),  -- Skullsplitter Crossbow
(9,415108,1378699,3750),  -- Martyr Cross Book
(9,415109,1378700,3750),  -- Mystic Druid Idol
(9,415111,1378702,2812),  -- Crystallized Amulet
(9,415112,1378703,2812),  -- Crystallized Wristguards
(9,415113,1378704,5000),  -- The Ironjaw
(8,415114,1378705,3750),  -- Stonesplitter
(9,415115,1378706,2812),  -- Fallen Gladiator's Shield
(9,415116,1378707,2812),  -- Nature's Defiance
(9,415117,1378708,5000),  -- Lazy Hat
(9,415118,1378709,2812),  -- Jubuwal Witchdoctor Amulet
(9,415119,1378710,2812),  -- Ring of Accurate Endeavors
(9,415120,1378711,5000),  -- Muckrake's Soup Bowl
(8,415121,1378712,3750),  -- Coldridge Crusher
(9,415122,1378713,5000),  -- Polished Alteraci Breastplate
(8,415123,1378714,3750),  -- Blood Soaked Spike
(8,415124,1378715,3750),  -- Syndicate Slicer
(9,415125,1378716,3750),  -- Feline's Grasp
(9,415126,1378717,3750),  -- Forgotten Warrior's Pauldrons
(9,415127,1378718,3750),  -- Ice-Forged Gauntlets
(9,415128,1378719,2812),  -- Tracker's Scope
(9,415129,1378720,3750),  -- Totem of the Flowing River
(9,415130,1378721,3750),  -- Tribal Pads
(9,415131,1378722,3750),  -- Safety Gloves
(8,415132,1378723,3750),  -- The Rock Binder
(9,415133,1378724,2812),  -- Spark of Infernus
(8,415134,1378725,3750),  -- Shadowforge Shotgun
(9,415135,1378726,2812),  -- Shadowforged Deflector
(8,415136,1378727,3750),  -- Toe Hammer
(9,415137,1378728,2812),  -- Bloodstained Pendant
(8,415138,1378729,5000),  -- Staff of the Earth Guardian
(8,415139,1378730,5000),  -- Real Big Bone
(9,415140,1378731,5000),  -- Garek's Comfortable Robe
(9,415141,1378732,3750),  -- Thorkaf's Prototype
(9,415142,1378733,5000),  -- Deflector's Wargreaves
(9,415143,1378734,2812),  -- Tomb Seeker
(8,415144,1378735,3750),  -- Tombscarred Guardian
(9,415145,1378736,3750),  -- Rock Runners
(9,415146,1378737,3750),  -- Stonewalker's Totem
(9,415147,1378738,2812),  -- Spellpiercing Cloak
(9,415148,1378739,2812),  -- Earth Bindings
(8,415149,1378740,5000),  -- Ogre Fire Poker
(9,415150,1378741,3750),  -- Stonebloom Idol
(9,415151,1378742,2812),  -- Ogre Cloth
(9,415152,1378743,3750),  -- Duelist Gloves
(8,415153,1378744,5000),  -- Dustbringer
(9,415154,1378745,2812),  -- Focusing Spirit Band
(8,415155,1378746,3750),  -- Bone Carver
(8,415156,1378747,3750),  -- Sunscorched Thrower
(9,415157,1378748,5000),  -- Ragescorn Circlet
(9,415158,1378749,3750),  -- Unearthed Pauldrons
(8,415159,1378750,3750),  -- Wind-Worn Longbow
(9,415160,1378751,5000),  -- Cowl of the Stone Summoner
(9,415161,1378752,5000),  -- Bloodstained Helm
(9,450238,1378753,3750),  -- Frostwalker Boots
(9,450239,1378754,2812),  -- Spicy Candle
(9,450240,1378755,2812),  -- Lost Adventurer's Ring
(9,450242,1378757,2812),  -- Glinting Necklace
(8,450243,1378758,5000),  -- Snow Shovel
(8,450244,1378759,3750),  -- Lumber Axe
(8,450245,1378760,3750),  -- Lost Mountaineer's Bow
(9,450246,1378761,2812),  -- Magnus' Mug
(8,450247,1378762,5000),  -- Chilly Pickaxe
(8,450248,1378763,3750),  -- Bone Needle
(9,450249,1378764,2812),  -- Gnomeregan Spanner
(9,450250,1378765,2812),  -- Sailor's Ring
(9,450251,1378766,2812),  -- Wendigo Fur Cloak
(8,450252,1378767,3750),  -- Frostmane Axe
(9,450253,1378768,2812),  -- Frozen Finger
(8,450254,1378769,5000),  -- Arctic Imbued Stick
(8,450256,1378770,3750),  -- Claw of Vagash
(8,450257,1378771,5000),  -- Heavy Ogre Axe
(9,450258,1378772,2812),  -- Grizlak's Candle
(8,450259,1378773,3750),  -- Large Buzzard Talon
(8,450260,1378774,5000),  -- Tunnel Rat Pike
(9,450261,1378775,5000),  -- Miner's League Vest
(8,450262,1378776,3750),  -- Sword of Stone
(8,450263,1378777,3750),  -- Galgosh's Other Bone
(9,450264,1378778,2812),  -- Brother's Special Gift
(8,450265,1378779,3750),  -- Ol' Blunderbuss
(9,450266,1378780,2812),  -- Dark Iron Collar
(9,450267,1378781,5000),  -- Ogre Loincloth
(9,450268,1378782,2812),  -- Frenzy Fin
(9,450269,1378783,2812),  -- Scrap Shield
(9,450270,1378784,2812),  -- Lost Traveler's Ring
(9,450271,1378785,2812),  -- Frayed Backwrap
(8,450272,1378786,3750),  -- Enchanted Scribe's Feather
(9,450273,1378787,2812),  -- Crater's Silk Drape
(9,450274,1378788,5000),  -- Runed Pantaloons
(9,450275,1378789,3750),  -- Charred Greaves
(9,450276,1378790,5000),  -- Dusty Sorcerer Hat
(9,450277,1378791,2812),  -- Chain of the Forgotten Prisoner
(8,450500,1378792,3750),  -- Worn Grunt Axe
(9,450502,1378794,2812),  -- Wristguards of the Elements
(9,450503,1378795,2812),  -- Sturdy Peon Blanket
(8,450504,1378796,5000),  -- Large Kodo Bone
(9,450505,1378797,2812),  -- Stolen Tauren Cloak
(8,450506,1378798,3750),  -- Ancestor's Axe
(9,450507,1378799,2812),  -- Aloof Tauren's Herb Incense
(9,450508,1378800,2812),  -- Burning Blade Ring
(9,450509,1378801,2812),  -- Bloodied Torn Bracers
(9,450511,1378803,2812),  -- Gem of Fortitude
(9,450512,1378804,2812),  -- Defias Special Bucket
(9,450514,1378806,3750),  -- Deadman Walkers
(8,450515,1378807,3750),  -- Mother's Loose Fang
(9,450517,1378808,2812),  -- Bones to Gnaw
(9,450518,1378809,2812),  -- Bones to Munch
(9,450519,1378810,2812),  -- Stormwind Memento
(9,450522,1378812,2812),  -- Murloc Voodoo Doll
(8,450523,1378813,3750),  -- Enchanted Straw Appendage
(9,450524,1378814,2812),  -- Lexicon Ring
(8,450525,1378815,3750),  -- Thunderfall Wand
(8,450526,1378816,3750),  -- Thunderfall Hunting Gun
(9,450527,1378817,2812),  -- Loop of the Sly Rogue
(9,450528,1378818,2812),  -- The Candle
(8,450529,1378819,3750),  -- Gnoll Subjugator
(9,450530,1378820,2812),  -- Rot Hide Mantle
(9,450531,1378821,2812),  -- Ravenous Eye
(9,450532,1378822,2812),  -- Alchemy Research Notes
(9,450533,1378823,5000),  -- Rot Hide Harness
(9,450534,1378824,2812),  -- Stolen Rot Hide Circlet
(9,450535,1378825,2812),  -- Thule's Curse Parchment
(8,450536,1378826,3750),  -- Grandpa's Scarlet Blade
(9,450537,1378827,2812),  -- Arcane Glinting Shard
(9,450538,1378829,2812),  -- Ancient Lordaeron Jewel
(9,450539,1378830,2812),  -- Sack of Pine Seeds
(9,450540,1378831,2812),  -- Ivar's Femur
(9,450541,1378832,2812),  -- Nightlash Gown
(8,450542,1378833,3750),  -- Small Claw of the Meat Wagon
(9,450543,1378834,2812),  -- Poison Unguent Extract
(9,450544,1378835,5000),  -- Gilnean Monocle
(9,450545,1378836,2812),  -- Grimson Cloak
(9,450546,1378837,2812),  -- Fenris Ring
(9,450547,1378838,2812),  -- Ravenclaw Bone Necklace
(9,450548,1378839,2812),  -- Corroded Quel'thalas Ring 
(9,450549,1378840,2812),  -- Worn Quel'thalas Heirloom
(9,450550,1378841,2812),  -- Old Quel'thalas Brooch
(9,450551,1378842,2812),  -- Fisherman's Last Wish
(9,450552,1378843,2812),  -- Peculiar Gold Nugget
(8,450553,1378844,5000),  -- Mrlrgrl Pitchfork
(9,450554,1378845,2812),  -- Rusty Quel'thalas Circlet
(9,450555,1378846,2812),  -- Murky Quel'thalas Drape
(8,450556,1378847,3750),  -- People's Militia Crossbow
(9,450557,1378848,2812),  -- Stolen Thunderbrew Flask
(9,450558,1378849,2812),  -- Terrible Defias Mixture
(9,450559,1378850,2812),  -- Madness Cursed Notes
(8,450560,1378851,5000),  -- Harvest Golem Scythe
(9,450561,1378852,2812),  -- People's Militia Badge
(9,450562,1378853,2812),  -- Defias Honorcode Memento
(8,450563,1378854,3750),  -- Defias Sprig
(8,450564,1378855,3750),  -- Old Defias Gun
(9,450565,1378856,2812),  -- Defias Assassin Cloak
(9,450566,1378857,2812),  -- Ring of the Lexicon
(9,450567,1378858,5000),  -- Dirtpaw Trousers
(9,450568,1378859,2812),  -- Yowler's Howl
(9,450569,1378860,2812),  -- Dragon Matriarch Cloak
(9,450570,1378861,2812),  -- Stolen Ilgalar Neckpiece
(9,450571,1378862,5000),  -- Blackrock Summoner's Garb
(9,450572,1378863,2812),  -- Shadowhide Claw
(8,450573,1378864,3750),  -- Blackrock Render
(9,450574,1378865,2812),  -- Three Corner Coil
(9,450575,1378866,2812),  -- Three Corner Carp
(9,450576,1378867,2812),  -- Three Corner Cape
(8,450577,1378868,5000),  -- Mrrrllrl Stick
(9,450578,1378869,2812),  -- Aqualon's Bolt
(9,450579,1378870,2812),  -- Thresher's Tooth
(9,450580,1378871,2812),  -- Ribchaser's Loop
(9,450581,1378872,2812),  -- Eliza's Pendant
(9,450582,1378873,2812),  -- Fullmoon Howl
(8,450583,1378874,3750),  -- Naraxis Fang
(9,450584,1378875,2812),  -- Haunted Bouquet
(9,450585,1378876,2812),  -- Gutspill Cloak
(9,450586,1378877,2812),  -- Sack of Regenerating Provisions
(9,450587,1378878,2812),  -- Nightwatch Circlet
(9,450588,1378879,2812),  -- Dusty Priest Cloak
(9,450589,1378880,2812),  -- Pack Lead Bone Ring
(8,450590,1378881,3750),  -- Defias Night Blade
(8,450591,1378882,3750),  -- Vul'Gol Torch
(9,450592,1378883,2812),  -- Venom Sample
(9,450593,1378884,2812),  -- Cursed Toy
(9,450594,1378885,2812),  -- The Jitters
(8,450595,1378886,3750),  -- Raven Hill Backscratcher
(9,450597,1378887,2812),  -- Casket Will
(9,450598,1378888,2812),  -- Catacombs Torch
(9,450599,1378889,2812),  -- Alchemy Visceral Juice
(9,450600,1378890,2812),  -- Ruby Skeletal Ring
(9,450601,1378891,2812),  -- Poisoned Pendant
(9,450602,1378892,2812),  -- Hazard Mantle
(8,450603,1378893,5000),  -- Peculiar Root
(9,450604,1378894,2812),  -- Darkest Night Loop
(9,450605,1378895,2812),  -- Munitions Delivery Package
(9,450606,1378896,2812),  -- Emerald Glinting Scale
(9,450607,1378897,3750),  -- Hope for Atonement
(8,450609,1378898,5000),  -- Bristleback Staff
(9,450610,1378899,2812),  -- Thornmantle Quills
(8,450611,1378900,3750),  -- Bristleback Quill
(8,450612,1378901,3750),  -- Brambleblade
(9,450613,1378902,2812),  -- Feather of the Mother Harpy
(9,450614,1378903,2812),  -- Venture Co. Unique Concoction
(8,450615,1378904,3750),  -- Fallen Hardwood Plank
(9,450616,1378905,2812),  -- Snaggle's Engage Whistle
(8,450617,1378906,5000),  -- Long Fishing Spear
(9,450618,1378907,2812),  -- Windfury Harpy Claw
(8,450619,1378908,5000),  -- Galak Smasher
(9,450620,1378909,2812),  -- Venture Co. Ring
(9,450621,1378910,2812),  -- Discarded Wagon Wheel
(9,450622,1378911,2812),  -- Interloper's Loop
(9,450623,1378912,2812),  -- Lyrath's Pan Flute
(9,450624,1378913,2812),  -- Amani Relic Amulet
(8,450625,1378914,5000),  -- Sin'dorei Battle Staff
(9,450626,1378915,2812),  -- Blight Potion
(8,450627,1378916,5000),  -- Scourge Blight Staff
(8,450628,1378917,3750),  -- Broken Windrunner Scotch Bottle
(9,450629,1378918,2812),  -- Goldenmist Everflowing Water
(9,450630,1378919,2812),  -- Crystalized Mana Wyrm Core
(8,450631,1378920,3750),  -- Blackpaw Scavenger Pick
(9,450632,1378921,2812),  -- Huntress Sentinel Ring
(9,450633,1378922,2812),  -- Fallen Eye Jewel
(8,450634,1378923,5000),  -- Dawnstar Paladin Claymore
(8,450635,1378924,3750),  -- Second War Axe
(9,450636,1378925,2812),  -- Ancient Amani Shield
(9,450637,1378926,2812),  -- An'owyn Fragment
(9,450638,1378927,2812),  -- Lost Bone Necklace
(9,450639,1378928,2812),  -- Loded Ring
(9,450640,1378929,2812),  -- Vial of Dread Water
(8,450641,1378930,3750),  -- Honor Blade
(9,450642,1378931,3750),  -- Wailing Sapphire Gem
(9,450643,1378932,2812),  -- Stylish Cloak
(9,450644,1378933,2812),  -- Bloody Wedding Ring
(8,450645,1378934,3750),  -- Northwatch Hand Cannon
(9,450646,1378935,5000),  -- Affray Cuirras
(9,450647,1378936,2812),  -- Captain's Spyglass
(8,450648,1378937,3750),  -- Overwatch Bow
(9,450649,1378938,2812),  -- Special Excavation Lantern
(9,450650,1378939,2812),  -- Burial Wraps
(9,450655,1378943,2812),  -- Sunstrider Wraps
(9,450657,1378945,2812),  -- Water Wraps
(8,450658,1378946,5000),  -- Worn Shovel
(8,450659,1378947,3750),  -- Patrolman's Sword
(8,450670,1378948,3750),  -- Drumstick
(8,450671,1378949,5000),  -- Fire Poker
(9,450673,1378951,2812),  -- Moonbathed Necklace
(8,450674,1378952,5000),  -- Glen Guardian
(9,450675,1378953,2812),  -- Lily Corsage
(8,450676,1378954,3750),  -- Tracker's Dagger
(9,450677,1378955,2812),  -- Webbed Cloak
(9,450678,1378956,2812),  -- Dripping Fang
(9,450681,1378959,2812),  -- Rabbit's Paw
(8,450682,1378960,3750),  -- Spine Hammer
(9,450683,1378961,3750),  -- Edan's Stripe
(8,450684,1378962,3750),  -- Salvaged Cannon
(9,450685,1378963,5000),  -- Dark Iron Vest
(9,450686,1378964,3750),  -- Thawed Boots
(9,450687,1378965,5000),  -- Voodoo Kilt
(8,450689,1378966,3750),  -- Centaur Axe
(8,450691,1378967,3750),  -- Treasured Cutlass
(8,450692,1378968,5000),  -- Logsplitter
(8,450694,1378969,5000),  -- Skull Sword
(8,450696,1378970,3750),  -- Quilbow
(9,450697,1378971,2812),  -- Raptorscale Cloak
(9,450700,1378972,3750),  -- Gardening Gloves
(9,450701,1378973,5000),  -- Defias Cowl
(9,450703,1378974,3750),  -- Silky Spaulders
(9,450705,1378975,2812),  -- Dustrunner Bindings
(8,450707,1378977,3750),  -- Assassin's Crossbow
(8,450709,1378978,3750),  -- Harpy Hunter
(9,450711,1378979,5000),  -- Sailor's Gambeson
(9,450712,1378980,3750),  -- Margoz' Spare Stompers
(9,450713,1378981,3750),  -- Farm Hands
(9,450717,1378982,2812),  -- Conscript's Wraps
(9,450718,1378983,2812),  -- Sailor's Cuffs
(9,450720,1378984,5000),  -- Retired Grunt's Chainmail
(9,450721,1378985,3750),  -- Heavy Boots
(9,450724,1378986,5000),  -- Grunt's Chain Leggings
(9,450729,1378987,2812),  -- Enchanted Kobold Lantern
(9,450740,1378988,2812),  -- Skull Ring
(9,450741,1378989,2812),  -- Bramble Shield
(8,450744,1378990,3750),  -- Throwing Rock
(9,450745,1378991,3750),  -- Southfury Totem
(9,450746,1378992,2812),  -- Burning Blade Mark
(8,450748,1378993,3750),  -- Defias Handshake
(8,450750,1378994,3750),  -- Totem Charged Mace
(8,450751,1378995,3750),  -- Retired Shadow Blade
(8,450752,1378996,5000),  -- Warsong Timbercleaver
(8,450753,1378997,5000),  -- Orcish Fishing Device
(8,450756,1378999,3750),  -- Maestra's Training Longbow
(9,450757,1379000,2812),  -- Thistlefur Fur Shroud
(9,450758,1379001,5000),  -- Old Arcanus Robe
(9,450762,1379002,5000),  -- Warm Whoolies
(8,450767,1379003,3750),  -- Poacher's Crossbow
(8,450768,1379004,3750),  -- Thunder Hide Tailspike
(9,450771,1379005,5000),  -- Padded Vest
(9,450773,1379006,3750),  -- Flexible Gloves
(9,450775,1379007,5000),  -- Field Trousers
(9,450780,1379008,5000),  -- Claw Scarred Mail
(9,450782,1379009,3750),  -- Miner Handwraps
(9,450788,1379010,2812),  -- String of Ears
(9,450789,1379011,2812),  -- Firestarter
(8,450799,1379012,5000),  -- Apprentice's Harpoon
(8,450803,1379013,5000),  -- Stormwitch Staff
(9,450805,1379014,3750),  -- Furbolg War Drum
(9,450806,1379015,2812),  -- Jar of Spiders
(8,450807,1379016,3750),  -- Bathran's Cursed Twig
(8,450809,1379017,3750),  -- Jack's Toothpicker
(8,450812,1379018,5000),  -- Ironbeard's Axe
(8,450816,1379020,3750),  -- Silverwing Grovekeeper's Bow
(9,450822,1379021,5000),  -- Party Pants
(9,450825,1379022,2812),  -- Wizard Wraps
(8,450827,1379024,3750),  -- Bristlebow
(8,450829,1379025,3750),  -- Nightshot
(9,450835,1379026,5000),  -- Suspiciously Brown Trousers
(9,450838,1379027,3750),  -- Adventurer Gloves
(9,450840,1379028,5000),  -- Soldier's Mail
(9,450850,1379029,2812),  -- Guide to Elven Restoration - Vol. I
(9,450860,1379030,2812),  -- Rosebud Ring
(9,450865,1379031,3750),  -- Frostmane Totem
(8,450869,1379032,3750),  -- Ulag's Cleaver
(8,450870,1379033,3750),  -- Heavy Iron Pan
(8,450871,1379034,3750),  -- Murder Machete
(8,450872,1379035,5000),  -- Heavy Logsplitter
(8,450873,1379036,5000),  -- Woodbreaker Mallet
(8,450874,1379037,5000),  -- Butchery Blade
(8,450876,1379038,3750),  -- Fallen Bow
(9,450877,1379039,2812),  -- Riding Cloak
(9,450882,1379040,5000),  -- Forgotten Trunks
(9,450885,1379041,2812),  -- Sunbands
(9,450909,1379043,2812),  -- Liquid Arcane
(9,450910,1379044,2812),  -- Tiloa's Flowers
(8,450919,1379045,5000),  -- Officer's Pike
(9,450920,1379046,2812),  -- Fel Infused Band
(8,450923,1379047,5000),  -- Mystral Staff
(8,450930,1379048,3750),  -- Haren's Tankard
(8,450931,1379049,3750),  -- Burial Blade
(8,450932,1379050,5000),  -- Sharpened Chopper
(8,450934,1379051,5000),  -- Sentinel's Blade
(8,450948,1379054,3750),  -- Bleakheart Piercer
(8,450979,1379055,5000),  -- Boar Harvester
(9,450980,1379056,2812),  -- Rider's Ring
(9,450981,1379057,2812),  -- Intact Wagon Wheel
(8,450983,1379058,5000),  -- Apprentice Staff
(8,450988,1379059,5000),  -- Sturdy Fishing Pole
(9,451023,1379061,2812),  -- Cursed Fire Scar Pendant
(9,451024,1379062,2812),  -- Elune Tear Fragment
(9,451025,1379063,2812),  -- Bloodtooth Neck
(9,451026,1379064,2812),  -- Repelling Necklace
(9,451027,1379065,2812),  -- Swashbuckler's Chain
(9,451046,1379066,2812),  -- Felforged Meteor Fragment
(9,451047,1379067,2812),  -- Echo of Aessina
(9,451048,1379068,2812),  -- Ursangous' Claw
(9,451049,1379069,2812),  -- Endless Moonwell Chalice
(9,451052,1379070,2812),  -- Etched Tablet
(8,451084,1379071,3750),  -- Heavy Bone
(8,451085,1379072,3750),  -- Stump Biter
(8,451088,1379073,5000),  -- The Dark Soul
(8,451096,1379075,5000),  -- Garren's Pitchfork
(9,451097,1379076,2812),  -- Haunted Ring
(9,451098,1379077,2812),  -- Captain's Shield
(8,451099,1379078,5000),  -- Murloc Ritual Staff
(8,451102,1379079,3750),  -- Peon Motivator
(8,451105,1379080,5000),  -- Waterlogged Musket
(8,451111,1379082,3750),  -- Defias Shanker
(8,451114,1379083,5000),  -- Sharpened Pike
(8,451117,1379084,5000),  -- Defias Magus Staff
(8,451123,1379085,5000),  -- Drudger Smash
(8,451129,1379087,3750),  -- Defias Toe Knife
(8,460000,1379090,3750),  -- Dwarven Demolition Kit
(9,500560,1379882,3926),  -- Lumberjack's Thick Gloves
(8,515003,1379091,3750),  -- Tarantula Hunter Rifle
(8,515004,1379092,5000),  -- Solliden Family Broom
(8,515005,1379093,5000),  -- Misplaced Pitchfork
(9,515006,1379094,2812),  -- Washed Ashore Bottle
(9,515007,1379095,2812),  -- Old Wagon Wheel
(8,515008,1379096,3750),  -- Puddle-jumper Dagger
(9,515009,1379097,5000),  -- Dalaran Mage Garb
(9,515010,1379098,2812),  -- Evil-Infused Cuffs
(9,515011,1379099,2812),  -- Deathstalker Cloak
(9,515012,1379100,2812),  -- Forsaken Stone Braid
(8,515013,1379101,3750),  -- Gravedigger's Delight
(9,515014,1379102,5000),  -- Agamand Farmer Trousers
(9,515015,1379103,2812),  -- Apothecary's Lantern
(8,515016,1379104,5000),  -- Haunted Mace
(9,515017,1379105,2812),  -- Faulty Stone Golem
(9,515018,1379106,2812),  -- Dwarven Explosive Barrel
(9,515019,1379107,5000),  -- Leftover Mining Trousers
(9,515020,1379108,2812),  -- Scarlet Insignia
(9,515021,1379109,3750),  -- Windshaper Wraps
(9,515022,1379110,2812),  -- Old Snapjaw Shell
(9,515023,1379111,2812),  -- Timelost Captain Shield
(8,515024,1379112,5000),  -- Hillsbrad Shovel
(8,515025,1379113,5000),  -- Mudsnout Effigy
(8,515026,1379114,3750),  -- Deadman's Dagger
(8,515027,1379115,3750),  -- Eroded Pit Fighter Knuckles
(9,515028,1379116,2812),  -- Twilight Bands
(9,515029,1379117,2812),  -- Furbolg War-drum
(8,515032,1379120,5000),  -- Agamand Walking Stick
(9,515033,1379121,3926),  -- Ghostflame Scripture
(8,515034,1379122,5000),  -- Moon-gnawed Bone Spire
(8,515035,1379123,3750),  -- Blackwood Torch
(8,515036,1379124,5000),  -- Hunk of Darkshore Driftwood
(8,515037,1379125,3750),  -- Fanatic's Cursed Blade
(9,515038,1379126,3750),  -- Ancient Highborne Tome
(8,515039,1379127,5000),  -- Ancient Family Heirloom
(9,515041,1379129,5000),  -- Foreman's Lightcap
(8,515043,1379131,3750),  -- Waterlogged Sparkler
(9,515045,1379133,2812),  -- Tide Turner
(9,515046,1379134,3750),  -- Enchanted Flora Waist
(9,515047,1379135,2812),  -- Unpleasant Ring
(9,515143,1379136,2812),  -- Moonlight Infused Band
(9,515144,1379137,2812),  -- Wild Tracker Bindings
(8,515145,1379138,3750),  -- Seamstress Scissors
(8,515146,1379139,3750),  -- Heartwood Cleaver
(9,515147,1379140,3750),  -- Lakebottom Treads
(8,515148,1379141,5000),  -- Shen'dralar Staff
(9,515149,1379142,3750),  -- Stolen Highborne Spaulders
(8,515150,1379143,3750),  -- Grasping Claw
(9,515151,1379144,3750),  -- Tome of the Valiant
(8,515152,1379145,5000),  -- Ogre Cleaver
(9,515153,1379146,5000),  -- Gordunni Thumbtack
(8,515154,1379147,5000),  -- Gnoll-Gnawed Bone Bat
(9,515155,1379148,3750),  -- Grim Totem
(9,515156,1379149,5000),  -- Grimtotem Outrider's Vest
(9,515157,1379150,3750),  -- Grimtotem Relic
(9,515158,1379151,3750),  -- Worn Angler Cord
(8,515159,1379152,3750),  -- Savage Crossbow
(9,515160,1379153,3750),  -- Gnoll Stompers
(8,515161,1379154,3750),  -- Bench Breaker
(9,515162,1379155,2812),  -- Secluded Soothsayer's Pipes
(9,515163,1379156,2812),  -- Ambercoil Pendant
(9,515164,1379157,2812),  -- Silithid Husk Shield
(9,515165,1379158,5234),  -- Shimmering Silithid Carapace
(9,515166,1379159,3750),  -- Bug Catchers
(9,515167,1379160,2812),  -- Beastpile Drape
(8,515168,1379161,3750),  -- Long-Clawed Gnoll Paw
(8,515169,1379162,3750),  -- Nightfallen Longbow
(8,515170,1379163,3750),  -- Denrunner Tomahawk
(9,515171,1379164,3750),  -- Torn Hide Spaulders
(8,515172,1379165,5000),  -- Woodpaw Greatblade
(9,515173,1379166,2812),  -- Orb of Isildien Echoes
(8,515174,1379167,3750),  -- Shattered Highborne Blade
(8,515175,1379168,3750),  -- Isildien Tender's Wand
(9,515176,1379169,2812),  -- Runestone Figurine
(9,515177,1379170,5000),  -- Ogre Kneepad
(9,515178,1379171,2812),  -- Necklace of the Sunken Empire
(9,515181,1379174,2812),  -- Yeti Napkin
(8,515182,1379175,3926),  -- Shen'dralar Slicer
(9,515183,1379176,5234),  -- Moon-Infused Breeches
(9,515184,1379177,3750),  -- Sentinel Wrap
(8,515185,1379178,3750),  -- Zapping Rod
(8,515186,1379179,3750),  -- Strider Shot
(9,515187,1379180,2944),  -- Strider Waist Piece
(9,515188,1379181,2812),  -- Band of Scales
(9,515189,1379182,2812),  -- Solarsal Pendant
(9,515190,1379183,2812),  -- Tidebaron's Sigil
(8,515191,1379184,5000),  -- Hatestrike
(9,515192,1379185,3926),  -- Tanner Gloves
(9,515193,1379186,2812),  -- Thunderfur Cloak
(9,515194,1379187,5234),  -- Crown of Stone
(9,515195,1379188,2944),  -- Dormant Dreamscale
(8,515196,1379189,3926),  -- Ravenwind Fangblade
(9,515197,1379190,2944),  -- Gilded Stone Bulwark
(9,515199,1379192,2944),  -- Ravenwind Codex
(9,515200,1379193,2944),  -- Zaetar's Lost Heirloom
(8,515201,1379194,5234),  -- Staff of Twin Blossoms
(9,515202,1379195,2812),  -- Forgotten Wristguards
(8,515203,1379196,3926),  -- Night Sentinel's Aim
(8,515204,1379197,3926),  -- Bloodscorn Ritual Kris
(9,515205,1379198,2944),  -- Accursed Yeti Horn
(9,515206,1379199,2944),  -- Buccaneer's Barrier
(9,515208,1379201,2812),  -- Scorched Bindings
(9,515209,1379202,3750),  -- Corrupted Dragon Eye
(8,515211,1379204,5000),  -- Blackhoof Warmaul
(8,515212,1379205,3750),  -- Missing Apprentice Wand
(8,515213,1379206,3750),  -- Venomsilk Spellblade
(9,515214,1379207,3750),  -- Mudcrush Shoulders
(8,515215,1379208,3750),  -- Singed Flintlock
(9,515216,1379209,2812),  -- Deserter's Last Resort
(9,515217,1379210,5000),  -- Bloodfen Prowler Vest
(8,515218,1379211,3750),  -- Bloodfen Talon
(8,515219,1379212,3750),  -- Emberstring Drakebow
(8,515220,1379213,5000),  -- Denflame Channeler
(8,515221,1379214,3750),  -- Enchanted Dragon Bone
(9,515222,1379215,2812),  -- Scalebane Pendant
(8,515223,1379216,5000),  -- Emberscale Greatsword
(9,515224,1379217,2812),  -- Emberheart Talisman
(9,515225,1379218,2812),  -- Wheel of Misfortune
(8,515226,1379219,3750),  -- Tidefury Cutlass
(8,515227,1379220,3750),  -- Buzzcoil Tongs
(9,515228,1379221,2812),  -- Cylla's Endless Potion
(9,515229,1379222,3750),  -- Stonemaul Crusher's Girdle
(9,515230,1379223,2812),  -- Marshfall Mantle
(8,515231,1379224,3750),  -- Salt Scoured Boarding Axe
(8,515232,1379225,3750),  -- Spotter's Rifle
(8,515233,1379226,5000),  -- Crokolisk Hunter
(8,515234,1379227,3750),  -- Primitive Murloc Skewer
(9,515235,1379228,3750),  -- Muck Trudgers
(9,515236,1379229,5000),  -- Northpoint Helmet
(9,515237,1379230,5000),  -- Brackish Spellweave Robe
(9,515238,1379231,2812),  -- Sturdy Coffin Lid
(9,515239,1379232,2812),  -- Swamplight Concoction
(9,515240,1379233,3750),  -- Bogcaller Totem
(9,515241,1379234,2944),  -- Idol of the Brooding Shadow
(9,515242,1379235,2944),  -- Tome of Sundered Souls
(9,515243,1379236,5234),  -- Shadowsilk Seared Cuirass
(8,515244,1379237,5000),  -- Golem Chunk
(9,515245,1379238,3750),  -- Shoulderpads of Deep Thinking
(9,515246,1379239,2812),  -- Glassweb Ward Shroud
(8,515247,1379240,3750),  -- Caravan Crossbow
(9,515248,1379241,2812),  -- Dorius' Shield
(9,515249,1379242,2812),  -- Stomped Diary
(9,515251,1379243,3750),  -- Magma Petting Mittens
(9,515252,1379244,3750),  -- Dark Iron Leatherpads
(9,515253,1379245,2812),  -- Scorching Lodepebble
(8,515254,1379246,5234),  -- Scorched Greatblade
(9,515255,1379247,3926),  -- Dark Iron Slippers
(8,515256,1379248,3926),  -- Fire Poker
(9,515257,1379249,3926),  -- Steam Pressure Totem
(9,515258,1379250,2812),  -- Eye of Twilight
(8,515259,1379251,3926),  -- Disciplinary Rifle
(8,515260,1379252,5000),  -- Contraband Magician Rod
(8,515261,1379253,5000),  -- Zamael's Corrupted Twilight
(9,515262,1379254,2812),  -- Slave Band
(8,515263,1379255,3926),  -- Dark Iron Scorcher
(9,515264,1379256,2944),  -- Heavy War Golem Rune
(8,515265,1379257,3926),  -- Freedom Falchion
(9,515266,1379258,5000),  -- Slave Worker Pantaloons
(9,515267,1379259,3926),  -- Break-time Gloves
(9,515268,1379260,2944),  -- Dark Iron Loop
(9,515269,1379261,2944),  -- Incendosaur Bone String
(9,515270,1379262,5234),  -- Dark Iron Legplates
(9,515271,1379263,2944),  -- Dark Iron Wristbands
(9,515272,1379264,2944),  -- Elder Pipe
(8,515273,1379265,3926),  -- Overseer's Mystic Wrench
(8,515274,1379266,3926),  -- Molten Fang Tooth
(9,515275,1379267,5234),  -- Scorched Mail Tunic
(8,515276,1379268,5234),  -- Cogbolt's Special
(8,515277,1379269,3926),  -- Burned Blade Shiv
(9,515278,1379270,5234),  -- Dark Iron Hood
(9,515279,1379271,3750),  -- Sharp Chain Belt
(9,515281,1379272,5234),  -- Nethergarde Mining Cap
(9,515282,1379273,2944),  -- Mo'arg Saw Shield
(9,515283,1379274,5000),  -- Nethergarde Foreman Chest
(9,515284,1379275,3750),  -- Runed Ogre Wrap
(9,515285,1379276,5234),  -- Ogre Finger Sleeve
(9,515286,1379277,2812),  -- Old War Wraps
(8,515287,1379278,5234),  -- Orcish Demon Slayer
(8,515288,1379279,5234),  -- Elvish Demon Reaver
(8,515289,1379280,3750),  -- Demon Claw
(8,515290,1379281,5234),  -- Evoker's Twisted Coil
(8,515291,1379282,5234),  -- Shadowsworn Reaper
(9,515292,1379283,3926),  -- Collector's Junk
(8,515293,1379284,3926),  -- Dreadweaver
(8,515294,1379285,5000),  -- Dreadmaul Head Smasher
(8,515295,1379286,3926),  -- Charred Slicer
(9,515296,1379287,3926),  -- Demon Kickers
(9,515297,1379288,2944),  -- Crude Voodoo Doll
(8,515298,1379289,5234),  -- Doomlord Slasher
(9,515299,1379290,3926),  -- Pauldron of the First War
(9,515300,1379291,2944),  -- Cursed Drape
(9,515301,1379292,3926),  -- Ancient Dragonmaw Token
(8,515302,1379293,3750),  -- Fallen Soldier's Shank
(9,515303,1379294,2944),  -- Doom Pendant
(9,515304,1379295,3750),  -- Bloodmage Coil
(9,515305,1379296,3926),  -- Lost Faith
(9,515306,1379297,2812),  -- Portal Fragment
(8,515312,1379298,5234),  -- Ror's Wrecker
(9,515313,1379299,5234),  -- Timelost Vestments
(9,515314,1379300,3750),  -- Emerald Circle Charm
(8,515315,1379301,3926),  -- Jadefire Bone Breaker
(9,515316,1379302,3926),  -- Lost Shipment Wristguards
(8,515317,1379303,5234),  -- Jadefire Piercer
(9,515318,1379304,2812),  -- Felhound Tendril
(9,515319,1379305,2944),  -- Bubbling Fel Mixture
(9,515320,1379306,3926),  -- Silverhand Spaulders
(9,515321,1379307,3926),  -- Xorothian Slippers
(8,515322,1379308,5234),  -- Jaednar Spire
(8,515324,1379310,3926),  -- Infernal Tender
(8,515325,1379311,3926),  -- Highborne Carver
(9,515326,1379312,2944),  -- Niby's Training Collar
(9,515327,1379313,2944),  -- Umbral Stalker's Tarp
(9,515328,1379314,5234),  -- Fallen Sentinel's Leggings
(9,515329,1379315,5234),  -- Ironwood Cap
(9,515330,1379316,2944),  -- Sindelle's Fuzzy Cuffs
(9,515331,1379317,2812),  -- Heart of the Warpwood
(9,515333,1379318,2944),  -- Crystal of Cruel Corruption
(8,515334,1379319,5234),  -- Talonbranch Sweeper
(9,515336,1379320,2944),  -- Timbermaw Defender
(9,515337,1379321,3926),  -- Timbermaw Girdle
(9,515338,1379322,2944),  -- Ring of Purity
(9,515339,1379323,2944),  -- Necklace of Purity
(8,515340,1379324,3926),  -- Acid Bolter
(8,515341,1379325,5234),  -- Fel Cleaver
(8,515342,1379326,5234),  -- Bitterbranch Claymore
(8,515343,1379327,3926),  -- Rotwood Sabre
(8,515354,1379328,3926),  -- Dinosaur Tranquilizer
(9,515355,1379329,2944),  -- Boom-Bling Choker
(9,515356,1379330,2812),  -- Cenarion Dreamcatcher
(8,515357,1379331,3750),  -- Marsh Shooter
(9,515358,1379332,2812),  -- Mystic Geode
(9,515360,1379333,2944),  -- Bug Repellant
(8,515361,1379334,3926),  -- Bonechipper Dagger
(9,515362,1379335,5234),  -- Jane's Lucky Hat
(9,515363,1379336,2812),  -- Silverback Cape
(8,515364,1379337,3926),  -- Tongs of Miscalibration
(8,515365,1379338,5234),  -- Pylon Charged Staff
(8,515366,1379339,3750),  -- Lost Fighter's Crossbow
(8,515367,1379340,5234),  -- Talon Ripper
(9,515368,1379341,5234),  -- Brand New Bikini
(9,515369,1379342,3750),  -- Idol of the Terror Claw
(8,515370,1379343,3926),  -- Dino Wacker
(9,515371,1379344,3926),  -- Wrangler's Cord
(9,515372,1379345,2944),  -- Thunderstomp Scale
(9,515373,1379346,2812),  -- Doomfall Spark
(9,515374,1379347,5234),  -- Retired Hero's Helm
(9,515375,1379348,2944),  -- Pterrodax Scale Cloak
(9,515376,1379349,2944),  -- Shifting Form
(9,515377,1379350,3926),  -- Serpent Spine Pauldrons
(9,515378,1379351,2944),  -- Sparkshard Necklace
(9,515379,1379352,3926),  -- Egg Thief's Handwraps
(8,515380,1379353,3926),  -- Qiraji Stinger
(8,515381,1379354,3926),  -- Cindersguard Saber
(8,515382,1379355,3926),  -- Ringo's Star
(9,515383,1379356,2944),  -- One Ring to Flame Them All
(9,515384,1379357,5234),  -- Ember Crown
(9,515385,1379358,3926),  -- Blaze Runners
(9,515386,1379359,3750),  -- Totem of Scorching Sparks
(8,515387,1379360,3926),  -- Molten Fang
(9,515388,1379361,2944),  -- Slightly Sticky Cloak
(9,515389,1379362,5000),  -- Golakka Scoured Legguards
(9,515390,1379363,3926),  -- Ballast Laden Pauldrons
(9,515391,1379364,2944),  -- Campsite Shrapnel
(9,515392,1379365,5234),  -- Carapace Plated Chest
(8,515393,1379366,5234),  -- Carapace Cracker
(9,515394,1379367,5234),  -- Crystal Fused Carapace
(8,515395,1379368,3926),  -- Gorishi Antenna
(9,515396,1379369,2944),  -- Cord of Living Vines
(9,515397,1379370,2944),  -- Elegantly Designed Cuffs
(9,515398,1379371,5234),  -- Silithid Ritual Robe
(9,515399,1379372,2812),  -- Ravasaur Talon
(8,515400,1379373,3926),  -- Tawana's Spare Axe
(8,515401,1379374,3750),  -- Caravaneer's Machete
(9,515402,1379375,3750),  -- Marsh Treaders
(8,515403,1379376,5000),  -- Caravan Utility Hammer
(8,515404,1379377,3926),  -- Jungle String Bow
(9,515405,1379378,5234),  -- Lucky Fisherman's Breeches
(9,515406,1379379,2812),  -- Water Dredger's Wrap
(9,515407,1379380,2812),  -- Expedition Bracers
(9,515409,1379382,3750),  -- Hexweave Gloves
(8,515410,1379383,3926),  -- Fossilized Smasher
(8,515411,1379384,5000),  -- Goblin Plant Slicer
(8,515413,1379386,3750),  -- Spring Shard
(9,515414,1379387,3926),  -- Libram of Ancient Warding
(9,515415,1379388,2944),  -- Prancefin Ring
(8,515425,1379389,3750),  -- Nightsong Waraxe
(9,515426,1379390,2812),  -- Mystral Compass
(9,515427,1379391,2812),  -- Fine Silk Wraps
(9,515428,1379392,2812),  -- Teldrassil Begonias
(9,515429,1379393,2812),  -- Torn Spellbook Page
(9,515430,1379394,2812),  -- Arlithrien Moon Orb
(9,515431,1379395,2812),  -- Lunar Tome
(9,515432,1379396,3750),  -- Whisperwind Boots
(8,515433,1379397,3750),  -- Timberling Dagger
(8,515434,1379398,3750),  -- Starfall Edge
(8,515435,1379399,5000),  -- Blade of the Submerged Moon
(9,515436,1379400,2812),  -- Whisperwind Heirloom
(8,515437,1379401,3750),  -- Timberbane Axe
(8,515438,1379402,3750),  -- Lifesap Blade
(9,515439,1379403,2812),  -- Spirited Cane
(8,515440,1379404,5000),  -- Blade of Severed Souls
(8,515441,1379405,5000),  -- Abandoned Fishing Rod
(8,515442,1379406,5000),  -- Rock Smasher
(8,515444,1379407,3750),  -- Dirge of the Dead
(8,515466,1379408,3750),  -- Alchemist's Ladel
(9,515502,1379409,2812),  -- Failed Parachute
(9,515503,1379410,3750),  -- Forgotten Pauldron
(8,515504,1379411,5000),  -- Grimtotem Darkblade
(8,515505,1379412,5000),  -- Centaur Mining Axe
(8,515506,1379413,5000),  -- Galak Chicken Smasher
(8,515507,1379414,5000),  -- Wyvern Trapper Spear
(9,515508,1379415,2812),  -- Highperch Necklace
(9,515509,1379416,2812),  -- Darkcloud Braid
(9,515510,1379417,2812),  -- Deadman's Signet
(9,515511,1379418,2812),  -- Drowned Diver's Ring
(8,515512,1379419,3750),  -- Grimtotem Jaw Smasher
(8,515513,1379420,3750),  -- Galak Shortbow
(8,515514,1379421,3750),  -- Cursed Elemental Scepter
(8,515515,1379422,3750),  -- Slightly Magical Kodo Bone
(9,515516,1379423,3750),  -- Darkcloud Totem
(9,515517,1379424,5000),  -- Highlands Vest
(9,515518,1379425,2812),  -- Caravaner's Bracers
(9,515520,1379427,2812),  -- Cloud Serpent Feather
(8,515524,1379428,3750),  -- Scuba Slayer's Blade
(9,515525,1379429,5000),  -- Drowned Diver's Helm
(9,515528,1379430,3750),  -- Tahonda Gauntlets
(9,515529,1379431,5000),  -- Pirate's Mail
(9,515530,1379432,2812),  -- Abandoned Moonshine
(9,515531,1379433,2812),  -- Pip's Rad Stone
(9,515532,1379434,5000),  -- Survivor's Trousers
(9,515533,1379435,2812),  -- Kodo War Drum
(8,515534,1379436,3750),  -- Silithid Bug Blaster
(9,515535,1379437,2812),  -- Isolated Inventor's Bulk
(8,515536,1379438,3750),  -- Runway Scraper
(9,515537,1379439,5000),  -- U.L.T.R.A Racing Goggles
(8,515538,1379440,5000),  -- Giant Wood Splinter
(8,515539,1379441,5000),  -- Ancient Jeweler's Staff
(9,515540,1379442,3750),  -- Goblin Racing Boots
(8,515541,1379443,3750),  -- The Tickler
(8,515599,1379445,3926),  -- Sacrificial Carver
(9,515600,1379446,2944),  -- Legashi Bracers
(9,515601,1379447,2944),  -- Eldara's Stargazer
(9,515602,1379448,3926),  -- Gauntlets of the Overlook
(9,515603,1379449,5234),  -- Cliffwalker Legplates
(9,515604,1379450,2944),  -- Lyre of the Grand Scribe
(8,515605,1379451,5234),  -- The Wrath of Arkkoroc
(9,515606,1379452,3926),  -- Idol of the Ocean's Depths
(8,515607,1379453,5234),  -- Hydraxian Staff
(9,515608,1379454,2944),  -- Ravencrest Signet
(9,515609,1379455,3926),  -- Spitelash Waistguards
(9,515610,1379456,5234),  -- Vanessa's Eyepatch
(9,515611,1379457,3926),  -- Hydra Hide Belt
(9,515612,1379458,3926),  -- Cilkeck's Gloves
(9,515613,1379459,2944),  -- Necklace of Unbroken Waves
(8,515614,1379460,3750),  -- Shahiar's Lost Horn
(9,515615,1379462,3926),  -- Deep Hydra's Scales
(9,515616,1379463,2944),  -- Scalebeard's Old Shell
(8,515617,1379464,5234),  -- Stormslicer
(9,515618,1379465,5234),  -- Thalassian Circlet
(8,515619,1379466,3926),  -- Azure Will
(9,515620,1379467,2944),  -- Crystalized Shield
(9,515621,1379468,2944),  -- Imitation of Zin-Eldari
(8,515622,1379469,3926),  -- Claws of the Lion
(9,515623,1379470,2944),  -- Might of Azshara
(9,515624,1379471,2812),  -- Beth'Amara Shard
(8,515625,1379472,3926),  -- Markri Turret
(9,515626,1379473,3926),  -- Shoulderguards of Zin-Malor
(8,515627,1379474,3926),  -- Claws of the Bear
(9,515628,1379475,3926),  -- The Bear Feet
(9,515629,1379476,2944),  -- Spitelash Warbanner
(9,515630,1379477,2944),  -- Burning Band
(8,515631,1379478,3926),  -- Ruinbreaker
(8,515632,1379479,3926),  -- Hand of the Cliffs
(8,515633,1379480,3926),  -- Elune's Glow
(8,515634,1379481,5234),  -- Ish'thel Falesh, Gaze of Eldara
(8,515676,1379482,5000),  -- The Compliance Crusher
(9,515677,1379483,5000),  -- Salma's Summer Dress
(9,515678,1379484,3750),  -- Field Boots
(9,515679,1379485,3750),  -- Pumpkin Smashers
(8,515680,1379486,3750),  -- Gnoll Cleaver
(9,515681,1379487,2812),  -- Harvester's Aegis
(8,515682,1379488,3750),  -- Defias Throwing Knife
(9,515683,1379489,2812),  -- Blessed Mail Wraps
(9,515684,1379490,5000),  -- Defias Apothecary Pants
(8,515685,1379491,5000),  -- Quarry Sledge
(8,515686,1379492,5000),  -- Harvest Scythe
(9,515687,1379493,5000),  -- Rower's Jerkin
(8,515688,1379494,3750),  -- Featherbeard's Bulwark Blaster
(8,515689,1379495,3750),  -- Zun'watha Cleaver
(8,515690,1379496,3750),  -- Overwatch Longrifle
(9,515691,1379497,5000),  -- Dwarven Drinking Pants
(9,515692,1379498,3750),  -- Anchorfoot Greaves
(9,515693,1379499,2812),  -- Highvale Wellband
(8,515694,1379500,3750),  -- Highvale Ranger Bow
(9,515695,1379501,5000),  -- Zipcoil's Zapper Cap
(8,515696,1379502,3750),  -- Hide Piercer
(9,515697,1379503,5234),  -- Hexweave Robes
(9,515698,1379504,3750),  -- Idol of the Broodmother
(9,515699,1379505,5234),  -- Brood Caller's Raiment
(9,515700,1379506,3750),  -- Broodsilk Gloves
(9,515701,1379507,3750),  -- Floodworn Shoulderguards
(9,515702,1379508,2944),  -- Aerie Faith Vambraces
(9,515703,1379509,3926),  -- Ooze Cleansed Shoulderpads
(9,515704,1379510,3926),  -- Drowned Link Belt
(9,515705,1379511,2944),  -- Soothsayer Shroud
(9,515706,1379512,2944),  -- Elder Highpeak's Keepsake
(8,515707,1379513,3750),  -- Hexcall Gavel
(8,515708,1379514,5234),  -- Blood Keeper's Staff
(9,515709,1379515,2944),  -- Zul Warder's Cloak
(9,515710,1379516,2944),  -- Ring of the Sunken Courier
(9,515711,1379517,2944),  -- Slime Coated Cloak
(8,515712,1379518,3926),  -- Sludge Hammer
(9,515713,1379519,2944),  -- Fort Defender Band
(8,515714,1379520,5234),  -- Vilebranch Beastlance
(9,515715,1379521,5234),  -- Shadowpounce Cowl
(9,515716,1379522,2812),  -- Terrapine Carapace
(9,515717,1379523,3926),  -- Idol of the Aerie
(9,515718,1379524,3750),  -- Revantusk Hide Steppers
(9,515719,1379525,5000),  -- Seabreeze Hauberk
(9,515720,1379526,2944),  -- Trapper's Lone Band
(9,515721,1379527,5000),  -- Bloodthread Leggings
(9,515722,1379528,2944),  -- Oozling Thoughtcore
(9,515723,1379529,3926),  -- Treads of the Verdant Threshold
(8,515724,1379530,3926),  -- Vilebranch Warthrower
(8,515725,1379531,3926),  -- Fleshcarver Athame
(8,515726,1379532,3926),  -- The Blood Talon
(9,515727,1379533,3926),  -- Shellsplitter Girdle
(8,515728,1379534,5234),  -- Flayer's Edge
(8,515729,1379535,3926),  -- Highnest Repeater
(8,515730,1379536,5234),  -- Blood Drinker
(8,515731,1379537,3926),  -- Vilebranch Ritual Dagger
(9,515732,1379538,3926),  -- Libram of Resolute Light
(8,515733,1379539,3926),  -- Wand of the Broodbound
(9,515734,1379540,2944),  -- High Cascade Cord
(8,515735,1379541,5234),  -- Desperate Defense
(9,515736,1379542,2944),  -- Tiki Shield
(9,515737,1379543,2812),  -- Dive's Instruction Manual
(9,515738,1379544,2944),  -- Inventor's Sand Band
(8,515739,1379545,3750),  -- Sandfury Blade
(8,515740,1379546,3926),  -- Time Stream Slasher
(8,515741,1379547,5234),  -- Ancestral Warblade
(9,515742,1379548,5000),  -- Wastewander Alchemist's Robe
(8,515743,1379549,5000),  -- Betrayer's Blade
(9,515744,1379550,3750),  -- Sandswept Binding
(9,515745,1379551,3750),  -- Deadman Gauntlets
(9,515747,1379552,5000),  -- Dustwhisper Legguards
(9,515748,1379553,2812),  -- Sand Cover
(9,515750,1379555,3926),  -- Watcher's Mantle
(9,515755,1379556,2944),  -- Explorer's Last Wish
(9,515764,1379557,5234),  -- Tender's Hat
(9,515765,1379558,5000),  -- Sky Guard's Cuirass
(9,515767,1379559,3926),  -- Hivebreakers' Ward
(8,515769,1379560,3926),  -- Venom-Infused Screwdriver
(9,515770,1379561,2812),  -- Lid of the Dead
(9,515771,1379562,2944),  -- Cyclok's Sanity
(9,515772,1379563,3750),  -- Dunemaul Warbelt
(9,515773,1379564,3750),  -- Treasure Seeker's Gloves
(8,515775,1379565,3926),  -- Carapace Carver
(8,515781,1379566,3926),  -- Hazzali Antenna
(8,515782,1379567,5234),  -- Last Stand
(9,515783,1379568,5234),  -- Chitinous Chest
(9,515791,1379569,2944),  -- Ancient Wagon Wheel
(9,515797,1379570,2812),  -- Blister Chain
(9,515798,1379571,5000),  -- Desert Trader's Pants
(9,515800,1379572,2944),  -- Treasure Seeking Lodestone
(8,515801,1379573,3926),  -- The Wingman
(9,515822,1379574,2944),  -- Sun Cover
(8,515823,1379575,3750),  -- Winkey's Misplaced Wrench
(8,515824,1379576,5000),  -- Water Binder
(9,515825,1379577,3750),  -- Diving Boots
(9,515826,1379578,5000),  -- Sea Legs
(8,515827,1379579,5000),  -- Hull Wood Hunk
(9,515828,1379580,2812),  -- Captain's Compass
(9,515829,1379581,3750),  -- Southsea Raider Gloves
(9,515830,1379582,2812),  -- Wave Wraps
(9,515834,1379583,2812),  -- Fisher's Misfortune
(9,515835,1379584,2812),  -- Lens of Questionable Visions
(9,515836,1379585,3750),  -- Noon's Shade Relic
(9,515837,1379586,5000),  -- Desert Gambeson
(8,515838,1379587,5234),  -- Dunemaul Crusher
(9,515839,1379588,5000),  -- Stylish Racing Hat
(8,515840,1379589,3750),  -- Sandfury Ritual Mace
(8,515841,1379590,3750),  -- Sandfury Boomerang
(8,515842,1379591,3750),  -- Sorrow Bolter
(9,515843,1379592,2944),  -- Southmoon Amulet
(9,515844,1379593,2812),  -- Seed of Overgrowth
(9,515900,1379594,3750),  -- Sand Stompers
(8,515901,1379595,3750),  -- Sandstalker
(9,515902,1379596,2812),  -- Duneshot Armguards
(8,515903,1379597,3750),  -- High Seas Axe
(9,515904,1379598,3750),  -- Sand Polished Pauldrons
(8,515906,1379599,5000),  -- Executioner's Axe
(8,515909,1379600,5234),  -- Dunecaller's Spire
(8,515954,1379601,3926),  -- Minstrel's Magic
(9,516037,1379602,2812),  -- Sturdy Spectral Ring
(9,521000,1379604,3750),  -- Rootbark Girdle
(9,521001,1379605,2812),  -- Patched Verdant Cloak
(8,521002,1379606,5000),  -- Moonwell Cane
(8,521003,1379607,5000),  -- Timber Maul
(9,521004,1379608,3750),  -- Saplingweave Handwraps
(9,521005,1379609,5000),  -- Thornpaw Trousers
(8,521006,1379610,3750),  -- Wildwood Shortbow
(9,521007,1379611,5000),  -- Gnarlpine Jerkin
(9,521008,1379612,2812),  -- Nightbreeze Armguards
(9,521009,1379613,3750),  -- Groveprowler Gloves
(8,521010,1379614,3750),  -- Chipped Sentinel Blade
(8,521011,1379615,3750),  -- Dewleaf Piercer
(8,521012,1379616,3750),  -- Bloodfeather Wand
(9,521013,1379617,2812),  -- Harpy Feather Drape
(9,521014,1379618,2812),  -- Trickster's Signet
(8,521015,1379619,3750),  -- Featherlight Bow
(8,521016,1379620,5000),  -- Starfall Splitter
(9,521017,1379621,5000),  -- Glenwhisper Robes
(9,521018,1379622,5000),  -- Starbloom Legwraps
(9,521019,1379623,3750),  -- Moonglade Cord
(9,521020,1379624,2812),  -- Aldrassil Bindings
(9,521021,1379625,5000),  -- Woodwalker Hauberk
(9,521022,1379626,2812),  -- Duskrunner Shield
(8,521023,1379627,3750),  -- Thornrunner Throwing Star
(8,521024,1379628,3750),  -- Gloomrider Rifle
(9,521027,1379630,2812),  -- Faded Gravecloth Cuffs
(9,521028,1379631,3750),  -- Old Waterlogged Boots
(8,521029,1379632,3750),  -- Agamand Sharpshooter
(9,521030,1379633,5000),  -- Nightfallen Jerkin
(9,521031,1379634,5000),  -- Rattlecage Warplate
(9,521032,1379635,3750),  -- Wailing Sash
(8,521033,1379636,3750),  -- Maggot Eye Musket
(9,521034,1379637,2812),  -- Ghostmoor Cloak
(9,521036,1379639,5000),  -- Coastline Vest
(9,521041,1379644,5000),  -- Hermit's Leggings
(9,521042,1379645,3750),  -- Farstrider's Grips
(9,521043,1379646,3750),  -- Crude Grimscale Sash
(9,521044,1379647,2812),  -- Decayed Cape
(8,521045,1379648,5000),  -- Rotten Greatblade
(8,521046,1379649,5000),  -- Riverwind Hammer
(8,521047,1379650,3750),  -- Spellribbon Wand
(8,521048,1379651,3750),  -- Silvermoon Musket
(8,521049,1379652,3750),  -- Rusty Falchion
(8,521050,1379653,3750),  -- Duskwither Hatchet
(8,521051,1379654,3750),  -- Farstrider Pounder
(8,521052,1379655,3750),  -- Scout's Slicer
(9,521053,1379656,3750),  -- Hawkrider Boots
(9,521054,1379657,2812),  -- Amani Band
(9,521055,1379658,5000),  -- Sunsail Chestguard
(9,521056,1379659,2812),  -- Faded Sunfeather Wraps
(9,521057,1379660,2812),  -- Dawnsworn Pendant
(9,521058,1379661,5000),  -- Apprentice Vestments
(9,521059,1379662,5000),  -- Dakota Steppe Greaves
(9,521060,1379663,3750),  -- Windstamp Gloves
(9,521061,1379664,3750),  -- Softbrush Sash
(9,521062,1379665,5000),  -- Stonebull Cloth
(9,521063,1379666,2812),  -- Palemane Threads
(9,521064,1379667,5000),  -- Thunderwalk Breastplate
(9,521065,1379668,2812),  -- Cloudchaser Pendant
(8,521066,1379669,5000),  -- Bael'dun Waraxe
(8,521067,1379670,3750),  -- Pilfered Bloodhoof Bow
(8,521068,1379671,3750),  -- Golden Plains Crossbow
(9,521069,1379672,3750),  -- Kodo Beast Idol
(9,521070,1379673,3750),  -- Windhoof Totem
(8,521071,1379674,5000),  -- Plainsblade
(8,521072,1379675,3750),  -- Skychaser Wand
(8,521073,1379676,3750),  -- Sunchaser Blade
(9,521074,1379677,3750),  -- Swiftfoot Slippers
(9,521075,1379678,2812),  -- Hawkrunner Bracers
(8,521076,1379679,3750),  -- Steppereaver Hatchet
(9,521079,1379681,5000),  -- Bloodtalon Vestments
(9,521080,1379682,3750),  -- Kul Tiras Handwraps
(9,521081,1379683,3750),  -- Redrock Sash
(9,521082,1379684,2812),  -- Kul Tiras Armplates
(9,521083,1379685,5000),  -- Charred Battlegreaves
(8,521084,1379686,3750),  -- Grunt's Old Knife
(9,521086,1379687,2812),  -- Tiragarde Drape
(8,521087,1379688,3750),  -- Rocktusk Poker
(8,521088,1379689,3750),  -- Crocolisk Deterrent
(8,521089,1379690,3750),  -- Earthshatterer Gavel
(8,521090,1379691,3750),  -- Searing Sands Focus
(9,521092,1379692,2812),  -- Champion's Band
(9,521093,1379693,3750),  -- Waterlogged Warbelt
(9,521094,1379694,5000),  -- Rusty Greaves
(9,521095,1379695,5000),  -- Stillpine Jerkin
(9,521096,1379696,5000),  -- Feathered Pants
(9,521097,1379697,3750),  -- Silvermyst Slippers
(9,521098,1379698,2812),  -- Wrathscale Bulwark
(9,521099,1379699,2812),  -- Wrathscale Banner
(9,521100,1379700,3750),  -- Crazed Kurken Libram
(8,521101,1379701,3750),  -- Darnassus Longbow
(8,521102,1379702,3750),  -- Skitter Blaster
(8,521103,1379703,3750),  -- Owlbeast Ritual Stick
(8,521104,1379704,3750),  -- Fish Gutter
(8,521105,1379705,5000),  -- Peasant Log Chopper
(8,521106,1379706,3750),  -- Stillpine Gavel
(8,521107,1379707,3750),  -- Blood Elf Dagger
(9,521108,1379708,2812),  -- Wreckage Signet
(9,521109,1379709,3750),  -- Alliance Cord
(9,521110,1379710,2812),  -- Ancient Highborne Choker
(8,521112,1379712,3750),  -- Silt Shore Hammer
(9,521115,1379713,2812),  -- Eastvale Buckler
(9,521116,1379714,2812),  -- Mauled Armplates
(9,521117,1379715,3750),  -- Honed Steel Axe
(9,521118,1379716,5000),  -- Plundered Goldshire Vanguard
(9,521119,1379717,3750),  -- Splinter Fist Cowl
(9,521120,1379718,2812),  -- Brightwood Gloves
(9,521121,1379719,5000),  -- Decayed Breeches
(9,521122,1379720,2812),  -- Traveler's Forest Cloak
(9,521123,1379721,2812),  -- Smuggled Stormwind Choker
(8,521124,1379722,5000),  -- Stolen Greatsword
(8,521125,1379723,3750),  -- Murloc Piercer
(9,521127,1379725,3750),  -- The Vanishing Strap
(9,521128,1379726,5000),  -- Fisherman's Jerkin
(9,521129,1379727,3750),  -- Pilfered Heirloom
(9,521130,1379728,3750),  -- Old Valgan Slippers
(9,521131,1379729,5000),  -- Darkstrand Kilt
(9,521132,1379730,3750),  -- Chain Belt of the Elements
(9,521133,1379731,2812),  -- Lordamere Cuffs
(9,521134,1379732,3750),  -- Feral Stitched Boots
(9,521135,1379733,3750),  -- Ravenclaw Infantry Gloves
(9,521136,1379734,5000),  -- Dalaran Robes
(8,521137,1379735,3750),  -- Dalaran Hatchet
(8,521139,1379736,5000),  -- Gilnean Lance
(8,521140,1379737,3750),  -- Gilnean Bolter
(8,521142,1379738,3750),  -- Mountaineer Hatchet
(9,521143,1379739,3750),  -- Dwarven Sandals
(9,521144,1379740,3750),  -- Tattered Shoulders
(9,521145,1379741,5000),  -- Stolen Mountaineer Chest
(9,521146,1379742,2812),  -- Old Stitched Bindings
(8,521147,1379743,5000),  -- Vermin Staff
(8,521148,1379744,3750),  -- Farstrider Crossbow
(9,521149,1379745,5000),  -- Thelsamar Hood
(9,521150,1379746,3750),  -- Dwarven Mail Gauntlets
(8,521151,1379747,5000),  -- Abandoned Greatsword
(9,521152,1379748,2812),  -- Grawmug's Cape
(9,521153,1379749,2812),  -- Earthenwind Band
(9,521154,1379750,2812),  -- Drowned Pendant
(9,521155,1379751,5000),  -- Spider Silk Vestments
(9,521156,1379752,3750),  -- Sinter Wive's Rope
(9,521157,1379753,3750),  -- Stoneflow Handwraps
(9,521158,1379754,2812),  -- Twilight Vale
(9,521159,1379755,5000),  -- Blackwood Jerkin
(9,521160,1379756,3750),  -- Shorebreeze Sabatons
(9,521161,1379757,5000),  -- Highborne Trousers
(8,521162,1379758,3750),  -- Auberdine Scimitar
(8,521163,1379759,3750),  -- Wild Longbow
(8,521164,1379760,5000),  -- Relicseeker Staff
(9,521165,1379761,5000),  -- Stormscale Guard
(9,521166,1379762,3750),  -- Moonrest Slippers
(9,521167,1379763,3750),  -- Bristle Pads
(8,521168,1379764,3750),  -- Silt Blade
(8,521169,1379765,5000),  -- Mystwood Glaive
(9,521170,1379766,2812),  -- Nazzivus Cover
(8,521171,1379767,3750),  -- Wildkin Kris
(9,521172,1379768,3750),  -- Bloodmyst Totem
(9,521173,1379769,3750),  -- Bloodwatch Libram
(8,521174,1379770,3750),  -- Bloodcursed Gavel
(8,521175,1379771,5000),  -- Epochbreaker Warmaul
(9,521178,1379772,5000),  -- Ghostclaw Vest
(9,521179,1379773,3750),  -- Blight Infused Mantle
(9,521180,1379774,3750),  -- Dreadscar Girdle
(9,521181,1379775,3750),  -- Darnassian Grips
(9,521182,1379776,5000),  -- Kel'gash's War Breeches
(9,521183,1379777,3750),  -- Tormentor's Boots
(9,521184,1379778,2812),  -- Old Lordaeron Cape
(9,521185,1379779,3750),  -- Sunseeker Libram
(9,521188,1379780,3750),  -- Venture Co. Spaulders
(9,521189,1379781,3750),  -- Waterlogged Gloves
(9,521190,1379782,3750),  -- Venture Co. Boots
(9,521191,1379783,3750),  -- Steelrider Girdle
(8,521192,1379784,5000),  -- Bramblestaff
(9,521193,1379785,3750),  -- Stormcall Totem
(8,521194,1379786,3750),  -- Venture Co. Dirk
(9,521195,1379787,2812),  -- Giant Qiraji Scale
(8,521196,1379788,3750),  -- Malgin's Barback
(8,521197,1379789,3750),  -- Takar's Old Wand
(8,521198,1379790,3750),  -- Bristleback Thorn
(8,521199,1379791,5000),  -- Blackthorn Splitter
(8,521200,1379792,5000),  -- Razorthorn Claymore
(8,521201,1379793,3750),  -- Thornweaver Mace
(9,521202,1379794,2812),  -- Dustdevil Cape
(9,521203,1379795,5000),  -- Plainstalker Vest
(9,521204,1379796,3750),  -- Venture Co. Sabatons
(9,521205,1379797,5000),  -- Savannah Cowl
(9,521206,1379798,3750),  -- Kodo Stompers
(9,521208,1379799,3750),  -- Gnoll Crafted Spaulder
(9,521209,1379800,5000),  -- Gnoll Cap
(9,521210,1379801,3750),  -- Alther's Chain Wrap
(9,521211,1379802,3750),  -- Stonewatch Handwraps
(9,521212,1379803,3750),  -- Tharil'zun's Trek Boots
(9,521213,1379804,2812),  -- Old Redridge Buckler
(8,521214,1379805,3750),  -- Mongrel Blade
(8,521215,1379806,5000),  -- Everstill Claymore
(8,521216,1379807,5000),  -- Blackrock Waraxe
(8,521217,1379808,3750),  -- Rusty Redridge Rifle
(8,521218,1379809,3750),  -- Adventurer's Crossbow
(8,521219,1379810,3750),  -- Tidecaller's Hammer
(9,521220,1379811,3750),  -- Old War Tome
(8,521222,1379812,3750),  -- Red Mage Wand
(9,521223,1379813,3750),  -- Charred Spaulders
(9,521224,1379814,2812),  -- Cliffwalker Cuffs
(9,521225,1379815,3750),  -- Sunsown Grips
(9,521226,1379816,5000),  -- Huntress Threads
(8,521227,1379817,3750),  -- Deepmoss Fang
(8,521228,1379818,3750),  -- Windsong Shortbow
(8,521229,1379819,3750),  -- Crossroads Short Sword
(9,521230,1379820,3750),  -- Talon Idol
(8,521231,1379821,3750),  -- Grimtotem Striker
(9,521233,1379822,5000),  -- Wyvern Vest
(9,521234,1379823,2812),  -- Helcular's Pendant
(9,521235,1379824,2812),  -- Darrow Silverband
(8,521236,1379825,3750),  -- Tracker's Blade
(8,521237,1379826,3750),  -- Camouflaged Bow
(8,521238,1379827,5000),  -- Oracle's Fishy Staff
(8,521239,1379828,3750),  -- Ray's Farmhand
(8,521240,1379829,3750),  -- Daggerspine Rod
(8,521241,1379830,5000),  -- Bear Decapitator
(9,521242,1379831,3750),  -- Brazie's Gauntlets
(9,521243,1379832,3750),  -- Syndicate Treads
(9,521244,1379833,3750),  -- Ancient Durnholde Girdle
(9,521245,1379834,3750),  -- Mismatched Shoulderpads
(9,521246,1379835,2812),  -- Heisen's Loop
(8,521248,1379836,3750),  -- Old Dragonmaw Cleaver
(9,521249,1379837,2812),  -- Borrowed Dark Iron Signet
(9,521250,1379838,3750),  -- Crude Bluegill Totem
(8,521251,1379839,5000),  -- Dragonmaw Ritual Staff
(8,521252,1379840,3750),  -- Dark Iron Harvester
(8,521253,1379841,5000),  -- Pilfered Stormpike Polearm
(8,521254,1379842,3750),  -- Swiftgear Sniper
(8,521255,1379843,3750),  -- Thelsamar Bow
(8,521256,1379844,3750),  -- Old Dragon Bone
(8,521257,1379845,3750),  -- Arakor Mace
(9,521258,1379846,3750),  -- Mirefin Belt
(9,521259,1379847,5000),  -- Raptor-Gnawed Cap
(9,521260,1379848,5000),  -- Vestments of the Unbound
(9,521261,1379849,3750),  -- Stubborn Dwarf Slippers
(9,521264,1379850,5000),  -- Hunter's Tunic
(9,521265,1379851,3750),  -- Malorne's Girdle
(9,521266,1379852,3750),  -- Rehomed Belt
(8,521267,1379853,5000),  -- Leyline Channeling Rod
(9,521268,1379854,3750),  -- Coldhewn Tanning Gloves
(8,521318,1379855,3750),  -- Roland's Striker
(9,521319,1379856,2812),  -- Infiltrator's Shield
(9,521320,1379857,5000),  -- Stardust Scoured Helmet
(8,521321,1379858,5000),  -- Honed Steel Axe
(9,521322,1379859,5000),  -- Splinter Fist Cowl
(9,521323,1379860,3750),  -- Brightwood Gloves
(8,824378,1379903,5234),  -- Ancient Femur
(9,824379,1379904,2944),  -- Voodoo Guardian
(8,824380,1379905,5234),  -- Triad's Spear
(9,824381,1379906,5234),  -- Sinister Garb
(8,824382,1379907,3926),  -- Old Northshire Bolter
(9,824383,1379908,3926),  -- Old Gardening Gloves
(8,824384,1379909,3926),  -- Shadewell Stabber
(9,824385,1379910,2944),  -- Forsaken Tome
(8,824386,1379911,3926),  -- Grimtotem Bow
(9,824387,1379912,2944),  -- Traitor's Last Kiss
(8,824388,1379913,3926),  -- Sun Touched Club
(9,824389,1379914,3926),  -- Ceremonial Gloves
(8,824390,1379915,3926),  -- Decayed Sharpshot
(8,824391,1379916,3926),  -- Sturdy Arrow
(8,824392,1379917,5234),  -- Cain's Oathblade
(9,824393,1379918,2944),  -- Deadman's Cover
(8,824394,1379919,3926),  -- Radiant Rifle
(8,824395,1379920,5234),  -- Ancient Battleaxe
(9,824396,1379921,5234),  -- Radiant Fanatic Helmet
(9,824397,1379922,2944),  -- Rocket Shrapnel
(9,824398,1379923,3926),  -- Vulture Cult Idol
(8,824399,1379924,3926),  -- Disciple String
(8,824400,1379925,5234),  -- Nest Thorn
(8,824401,1379926,3926),  -- Carrion Eye
(8,1262811,1379865,3926),  -- Abomination Hook
(8,3595662,1379867,3750),  -- Dwarven Crossbow
(8,4050651,1379868,5000),  -- Sunken Zoram Spear
(9,4050652,1379869,5000),  -- Elven Militia Crown
(9,4050653,1379870,2812);  -- Pristine Tortoise Carapace
