-- Generated by worldforged-werkzeug/sql_bauen.py. Do not edit by hand.
--
-- The Worldforged upgrade recipes, rebuilt from the client's own data: the
-- family of an upgrade is stored in ItemAddon.dbc, where column f40 of the
-- upgraded variant points at its base item. 1738 first-rank upgrades survive
-- that way, 651 weapons and 1087 pieces of armour, and every base and target
-- row already exists in item_template.
--
-- The cost is NOT recovered. No captured store response survives and no
-- ItemExtendedCost row names a Worldforged base item. The numbers are computed
-- from Blizzard's own slot weights, so the progression follows a known logic
-- rather than an invented one. Replace the column and nothing else changes.

-- Where he stood is NOT recovered. There is no spawn row for him in the world
-- database, none in the backup, no AreaPOI entry for a call board or for the
-- guardian, and no coordinate in the call board Lua.
--
-- These two are therefore chosen, not recovered: walked to and read off with
-- `.gps`, out in the open where players pass, not inside an auction house.
-- Player reports place him beside the call boards; should those ever turn up
-- as spawns, move him with `.npc move` and rewrite this file.
DELETE FROM `creature` WHERE `id` = 9780012;
INSERT INTO `creature`
 (`id`,`map`,`spawnMask`,`phaseMask`,`equipment_id`,
  `position_x`,`position_y`,`position_z`,`orientation`,
  `spawntimesecs`,`wander_distance`,`currentwaypoint`,`curhealth`,`curmana`,
  `MovementType`)
VALUES
(9780012,0,1,1,0,-8821.6440,626.9797,93.81092,3.79461,300,0,0,0,0,0),  -- Stormwind, Trade District
(9780012,1,1,1,0,1578.5745,-4416.4736,8.03063,3.38266,300,0,0,0,0,0);  -- Orgrimmar, Valley of Strength
